/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.BadCredentialsError = factory(root.FinApiResTfulServices.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The BadCredentialsError model module.
   * @module model/BadCredentialsError
   * @version v1.92.0
   */

  /**
   * Constructs a new <code>BadCredentialsError</code>.
   * @alias module:model/BadCredentialsError
   * @class
   * @param error {String} Error type
   * @param errorDescription {String} Error description
   */
  var exports = function(error, errorDescription) {
    this.error = error;
    this.errorDescription = errorDescription;
  };

  /**
   * Constructs a <code>BadCredentialsError</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BadCredentialsError} obj Optional instance to populate.
   * @return {module:model/BadCredentialsError} The populated <code>BadCredentialsError</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('error'))
        obj.error = ApiClient.convertToType(data['error'], 'String');
      if (data.hasOwnProperty('error_description'))
        obj.errorDescription = ApiClient.convertToType(data['error_description'], 'String');
    }
    return obj;
  }

  /**
   * Error type
   * @member {String} error
   */
  exports.prototype.error = undefined;

  /**
   * Error description
   * @member {String} errorDescription
   */
  exports.prototype.errorDescription = undefined;

  return exports;

}));
