/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.BankConnectionOwner = factory(root.FinApiResTfulServices.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The BankConnectionOwner model module.
   * @module model/BankConnectionOwner
   * @version v1.92.0
   */

  /**
   * Constructs a new <code>BankConnectionOwner</code>.
   * Container for a bank connection owner's data
   * @alias module:model/BankConnectionOwner
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>BankConnectionOwner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BankConnectionOwner} obj Optional instance to populate.
   * @return {module:model/BankConnectionOwner} The populated <code>BankConnectionOwner</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('firstName'))
        obj.firstName = ApiClient.convertToType(data['firstName'], 'String');
      if (data.hasOwnProperty('lastName'))
        obj.lastName = ApiClient.convertToType(data['lastName'], 'String');
      if (data.hasOwnProperty('salutation'))
        obj.salutation = ApiClient.convertToType(data['salutation'], 'String');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('dateOfBirth'))
        obj.dateOfBirth = ApiClient.convertToType(data['dateOfBirth'], 'String');
      if (data.hasOwnProperty('postCode'))
        obj.postCode = ApiClient.convertToType(data['postCode'], 'String');
      if (data.hasOwnProperty('country'))
        obj.country = ApiClient.convertToType(data['country'], 'String');
      if (data.hasOwnProperty('city'))
        obj.city = ApiClient.convertToType(data['city'], 'String');
      if (data.hasOwnProperty('street'))
        obj.street = ApiClient.convertToType(data['street'], 'String');
      if (data.hasOwnProperty('houseNumber'))
        obj.houseNumber = ApiClient.convertToType(data['houseNumber'], 'String');
    }
    return obj;
  }

  /**
   * First name
   * @member {String} firstName
   */
  exports.prototype.firstName = undefined;

  /**
   * Last name
   * @member {String} lastName
   */
  exports.prototype.lastName = undefined;

  /**
   * Salutation
   * @member {String} salutation
   */
  exports.prototype.salutation = undefined;

  /**
   * Title
   * @member {String} title
   */
  exports.prototype.title = undefined;

  /**
   * Email
   * @member {String} email
   */
  exports.prototype.email = undefined;

  /**
   * Date of birth (in format 'YYYY-MM-DD')
   * @member {String} dateOfBirth
   */
  exports.prototype.dateOfBirth = undefined;

  /**
   * Post code
   * @member {String} postCode
   */
  exports.prototype.postCode = undefined;

  /**
   * Country
   * @member {String} country
   */
  exports.prototype.country = undefined;

  /**
   * City
   * @member {String} city
   */
  exports.prototype.city = undefined;

  /**
   * Street
   * @member {String} street
   */
  exports.prototype.street = undefined;

  /**
   * House number
   * @member {String} houseNumber
   */
  exports.prototype.houseNumber = undefined;

  return exports;

}));
