/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BankConsent', 'model/LoginCredentialResource', 'model/TwoStepProcedure', 'model/UpdateResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BankConsent'), require('./LoginCredentialResource'), require('./TwoStepProcedure'), require('./UpdateResult'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.BankConnectionInterface = factory(root.FinApiResTfulServices.ApiClient, root.FinApiResTfulServices.BankConsent, root.FinApiResTfulServices.LoginCredentialResource, root.FinApiResTfulServices.TwoStepProcedure, root.FinApiResTfulServices.UpdateResult);
  }
}(this, function(ApiClient, BankConsent, LoginCredentialResource, TwoStepProcedure, UpdateResult) {
  'use strict';

  /**
   * The BankConnectionInterface model module.
   * @module model/BankConnectionInterface
   * @version v1.92.0
   */

  /**
   * Constructs a new <code>BankConnectionInterface</code>.
   * Resource representing a bank connection interface
   * @alias module:model/BankConnectionInterface
   * @class
   * @param _interface {module:model/BankConnectionInterface.InterfaceEnum} Bank interface. Possible values:<br><br>&bull; <code>FINTS_SERVER</code> - means that finAPI will download data via the bank's FinTS interface.<br>&bull; <code>WEB_SCRAPER</code> - means that finAPI will parse data from the bank's online banking website.<br>&bull; <code>XS2A</code> - means that finAPI will download data via the bank's XS2A interface.<br>
   */
  var exports = function(_interface) {
    this._interface = _interface;
  };

  /**
   * Constructs a <code>BankConnectionInterface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BankConnectionInterface} obj Optional instance to populate.
   * @return {module:model/BankConnectionInterface} The populated <code>BankConnectionInterface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('interface'))
        obj._interface = ApiClient.convertToType(data['interface'], 'String');
      if (data.hasOwnProperty('loginCredentials'))
        obj.loginCredentials = ApiClient.convertToType(data['loginCredentials'], [LoginCredentialResource]);
      if (data.hasOwnProperty('defaultTwoStepProcedureId'))
        obj.defaultTwoStepProcedureId = ApiClient.convertToType(data['defaultTwoStepProcedureId'], 'String');
      if (data.hasOwnProperty('twoStepProcedures'))
        obj.twoStepProcedures = ApiClient.convertToType(data['twoStepProcedures'], [TwoStepProcedure]);
      if (data.hasOwnProperty('aisConsent'))
        obj.aisConsent = BankConsent.constructFromObject(data['aisConsent']);
      if (data.hasOwnProperty('lastManualUpdate'))
        obj.lastManualUpdate = UpdateResult.constructFromObject(data['lastManualUpdate']);
      if (data.hasOwnProperty('lastAutoUpdate'))
        obj.lastAutoUpdate = UpdateResult.constructFromObject(data['lastAutoUpdate']);
    }
    return obj;
  }

  /**
   * Bank interface. Possible values:<br><br>&bull; <code>FINTS_SERVER</code> - means that finAPI will download data via the bank's FinTS interface.<br>&bull; <code>WEB_SCRAPER</code> - means that finAPI will parse data from the bank's online banking website.<br>&bull; <code>XS2A</code> - means that finAPI will download data via the bank's XS2A interface.<br>
   * @member {module:model/BankConnectionInterface.InterfaceEnum} _interface
   */
  exports.prototype._interface = undefined;

  /**
   * Login fields for this interface, in the order that we suggest to show them to the user.
   * @member {Array.<module:model/LoginCredentialResource>} loginCredentials
   */
  exports.prototype.loginCredentials = undefined;

  /**
   * The default two-step-procedure for this interface. Must match one of the available 'procedureId's from the 'twoStepProcedures' list. When this field is set, then finAPI will automatically try to select the procedure wherever applicable. Note that the list of available procedures of a bank connection may change as a result of an update of the connection, and if this field references a procedure that is no longer available after an update, finAPI will automatically clear the default procedure (set it to null).
   * @member {String} defaultTwoStepProcedureId
   */
  exports.prototype.defaultTwoStepProcedureId = undefined;

  /**
   * Available two-step-procedures in this interface, used for submitting a money transfer or direct debit request (see /accounts/requestSepaMoneyTransfer or /requestSepaDirectDebit),or for multi-step-authentication during bank connection import or update. The available two-step-procedures mya be re-evaluated each time this bank connection is updated (/bankConnections/update). This means that this list may change as a result of an update.
   * @member {Array.<module:model/TwoStepProcedure>} twoStepProcedures
   */
  exports.prototype.twoStepProcedures = undefined;

  /**
   * If this field is set, it means that this interface is handing out a consent to finAPI in exchange for the login credentials. finAPI needs to use this consent to get access to the account list and account data (i.e. Account Information Services, AIS). If this field is not set, it means that this interface does not use such consents.
   * @member {module:model/BankConsent} aisConsent
   */
  exports.prototype.aisConsent = undefined;

  /**
   * Result of the last manual update of the associated bank connection using this interface. If no manual update has ever been done so far with this interface, then this field will not be set.
   * @member {module:model/UpdateResult} lastManualUpdate
   */
  exports.prototype.lastManualUpdate = undefined;

  /**
   * Result of the last auto update of the associated bank connection using this interface (ran by finAPI's automatic batch update process). If no auto update has ever been done so far with this interface, then this field will not be set.
   * @member {module:model/UpdateResult} lastAutoUpdate
   */
  exports.prototype.lastAutoUpdate = undefined;


  /**
   * Allowed values for the <code>_interface</code> property.
   * @enum {String}
   * @readonly
   */
  exports.InterfaceEnum = {
    /**
     * value: "WEB_SCRAPER"
     * @const
     */
    WEB_SCRAPER: "WEB_SCRAPER",

    /**
     * value: "FINTS_SERVER"
     * @const
     */
    FINTS_SERVER: "FINTS_SERVER",

    /**
     * value: "XS2A"
     * @const
     */
    xS2A: "XS2A"
  };

  return exports;

}));
