/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Category'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Category'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.CategorizationCheckResult = factory(root.FinApiResTfulServices.ApiClient, root.FinApiResTfulServices.Category);
  }
}(this, function(ApiClient, Category) {
  'use strict';

  /**
   * The CategorizationCheckResult model module.
   * @module model/CategorizationCheckResult
   * @version v1.92.0
   */

  /**
   * Constructs a new <code>CategorizationCheckResult</code>.
   * @alias module:model/CategorizationCheckResult
   * @class
   * @param transactionId {String} Transaction identifier
   */
  var exports = function(transactionId) {
    this.transactionId = transactionId;
  };

  /**
   * Constructs a <code>CategorizationCheckResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CategorizationCheckResult} obj Optional instance to populate.
   * @return {module:model/CategorizationCheckResult} The populated <code>CategorizationCheckResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('transactionId'))
        obj.transactionId = ApiClient.convertToType(data['transactionId'], 'String');
      if (data.hasOwnProperty('category'))
        obj.category = Category.constructFromObject(data['category']);
    }
    return obj;
  }

  /**
   * Transaction identifier
   * @member {String} transactionId
   */
  exports.prototype.transactionId = undefined;

  /**
   * Category
   * @member {module:model/Category} category
   */
  exports.prototype.category = undefined;

  return exports;

}));
