/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MultiStepAuthenticationChallenge'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MultiStepAuthenticationChallenge'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.ErrorDetails = factory(root.FinApiResTfulServices.ApiClient, root.FinApiResTfulServices.MultiStepAuthenticationChallenge);
  }
}(this, function(ApiClient, MultiStepAuthenticationChallenge) {
  'use strict';

  /**
   * The ErrorDetails model module.
   * @module model/ErrorDetails
   * @version v1.92.0
   */

  /**
   * Constructs a new <code>ErrorDetails</code>.
   * Error details
   * @alias module:model/ErrorDetails
   * @class
   * @param code {module:model/ErrorDetails.CodeEnum} Error code. See the documentation of the individual services for details about what values may be returned.
   * @param type {module:model/ErrorDetails.TypeEnum} Error type. BUSINESS errors depict error messages in the language of the bank (or the preferred language) for the user, e.g. from a bank server. TECHNICAL errors are meant to be read by developers and depict internal errors.
   */
  var exports = function(code, type) {
    this.code = code;
    this.type = type;
  };

  /**
   * Constructs a <code>ErrorDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ErrorDetails} obj Optional instance to populate.
   * @return {module:model/ErrorDetails} The populated <code>ErrorDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('multiStepAuthentication'))
        obj.multiStepAuthentication = MultiStepAuthenticationChallenge.constructFromObject(data['multiStepAuthentication']);
    }
    return obj;
  }

  /**
   * Error message
   * @member {String} message
   */
  exports.prototype.message = undefined;

  /**
   * Error code. See the documentation of the individual services for details about what values may be returned.
   * @member {module:model/ErrorDetails.CodeEnum} code
   */
  exports.prototype.code = undefined;

  /**
   * Error type. BUSINESS errors depict error messages in the language of the bank (or the preferred language) for the user, e.g. from a bank server. TECHNICAL errors are meant to be read by developers and depict internal errors.
   * @member {module:model/ErrorDetails.TypeEnum} type
   */
  exports.prototype.type = undefined;

  /**
   * This field is set when a multi-step authentication is required, i.e. when you need to repeat the original service call and provide additional data. The field contains information about what additional data is required.
   * @member {module:model/MultiStepAuthenticationChallenge} multiStepAuthentication
   */
  exports.prototype.multiStepAuthentication = undefined;


  /**
   * Allowed values for the <code>code</code> property.
   * @enum {String}
   * @readonly
   */
  exports.CodeEnum = {
    /**
     * value: "MISSING_FIELD"
     * @const
     */
    MISSING_FIELD: "MISSING_FIELD",

    /**
     * value: "UNKNOWN_ENTITY"
     * @const
     */
    UNKNOWN_ENTITY: "UNKNOWN_ENTITY",

    /**
     * value: "METHOD_NOT_ALLOWED"
     * @const
     */
    METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",

    /**
     * value: "ENTITY_EXISTS"
     * @const
     */
    ENTITY_EXISTS: "ENTITY_EXISTS",

    /**
     * value: "ILLEGAL_ENTITY_STATE"
     * @const
     */
    ILLEGAL_ENTITY_STATE: "ILLEGAL_ENTITY_STATE",

    /**
     * value: "UNEXPECTED_ERROR"
     * @const
     */
    UNEXPECTED_ERROR: "UNEXPECTED_ERROR",

    /**
     * value: "ILLEGAL_FIELD_VALUE"
     * @const
     */
    ILLEGAL_FIELD_VALUE: "ILLEGAL_FIELD_VALUE",

    /**
     * value: "UNAUTHORIZED_ACCESS"
     * @const
     */
    UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",

    /**
     * value: "BAD_REQUEST"
     * @const
     */
    BAD_REQUEST: "BAD_REQUEST",

    /**
     * value: "UNSUPPORTED_ORDER"
     * @const
     */
    UNSUPPORTED_ORDER: "UNSUPPORTED_ORDER",

    /**
     * value: "ILLEGAL_PAGE_SIZE"
     * @const
     */
    ILLEGAL_PAGE_SIZE: "ILLEGAL_PAGE_SIZE",

    /**
     * value: "INVALID_FILTER_OPTIONS"
     * @const
     */
    INVALID_FILTER_OPTIONS: "INVALID_FILTER_OPTIONS",

    /**
     * value: "TOO_MANY_IDS"
     * @const
     */
    TOO_MANY_IDS: "TOO_MANY_IDS",

    /**
     * value: "BANK_SERVER_REJECTION"
     * @const
     */
    BANK_SERVER_REJECTION: "BANK_SERVER_REJECTION",

    /**
     * value: "IBAN_ONLY_MONEY_TRANSFER_NOT_SUPPORTED"
     * @const
     */
    IBAN_ONLY_MONEY_TRANSFER_NOT_SUPPORTED: "IBAN_ONLY_MONEY_TRANSFER_NOT_SUPPORTED",

    /**
     * value: "IBAN_ONLY_DIRECT_DEBIT_NOT_SUPPORTED"
     * @const
     */
    IBAN_ONLY_DIRECT_DEBIT_NOT_SUPPORTED: "IBAN_ONLY_DIRECT_DEBIT_NOT_SUPPORTED",

    /**
     * value: "COLLECTIVE_MONEY_TRANSFER_NOT_SUPPORTED"
     * @const
     */
    COLLECTIVE_MONEY_TRANSFER_NOT_SUPPORTED: "COLLECTIVE_MONEY_TRANSFER_NOT_SUPPORTED",

    /**
     * value: "INVALID_TWO_STEP_PROCEDURE"
     * @const
     */
    INVALID_TWO_STEP_PROCEDURE: "INVALID_TWO_STEP_PROCEDURE",

    /**
     * value: "MISSING_TWO_STEP_PROCEDURE"
     * @const
     */
    MISSING_TWO_STEP_PROCEDURE: "MISSING_TWO_STEP_PROCEDURE",

    /**
     * value: "UNSUPPORTED_MEDIA_TYPE"
     * @const
     */
    UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",

    /**
     * value: "UNSUPPORTED_BANK"
     * @const
     */
    UNSUPPORTED_BANK: "UNSUPPORTED_BANK",

    /**
     * value: "USER_NOT_VERIFIED"
     * @const
     */
    USER_NOT_VERIFIED: "USER_NOT_VERIFIED",

    /**
     * value: "USER_ALREADY_VERIFIED"
     * @const
     */
    USER_ALREADY_VERIFIED: "USER_ALREADY_VERIFIED",

    /**
     * value: "INVALID_TOKEN"
     * @const
     */
    INVALID_TOKEN: "INVALID_TOKEN",

    /**
     * value: "LOCKED"
     * @const
     */
    LOCKED: "LOCKED",

    /**
     * value: "NO_ACCOUNTS_FOR_TYPE_LIST"
     * @const
     */
    NO_ACCOUNTS_FOR_TYPE_LIST: "NO_ACCOUNTS_FOR_TYPE_LIST",

    /**
     * value: "FORBIDDEN"
     * @const
     */
    FORBIDDEN: "FORBIDDEN",

    /**
     * value: "NO_EXISTING_CHALLENGE"
     * @const
     */
    NO_EXISTING_CHALLENGE: "NO_EXISTING_CHALLENGE",

    /**
     * value: "ADDITIONAL_AUTHENTICATION_REQUIRED"
     * @const
     */
    ADDITIONAL_AUTHENTICATION_REQUIRED: "ADDITIONAL_AUTHENTICATION_REQUIRED",

    /**
     * value: "WEB_FORM_REQUIRED"
     * @const
     */
    WEB_FORM_REQUIRED: "WEB_FORM_REQUIRED",

    /**
     * value: "WEB_FORM_ABORTED"
     * @const
     */
    WEB_FORM_ABORTED: "WEB_FORM_ABORTED",

    /**
     * value: "INVALID_CONSENT"
     * @const
     */
    INVALID_CONSENT: "INVALID_CONSENT",

    /**
     * value: "NO_CERTIFICATE"
     * @const
     */
    NO_CERTIFICATE: "NO_CERTIFICATE",

    /**
     * value: "NO_TPP_CLIENT_CREDENTIALS"
     * @const
     */
    NO_TPP_CLIENT_CREDENTIALS: "NO_TPP_CLIENT_CREDENTIALS"
  };


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "BUSINESS"
     * @const
     */
    BUSINESS: "BUSINESS",

    /**
     * value: "TECHNICAL"
     * @const
     */
    TECHNICAL: "TECHNICAL"
  };

  return exports;

}));
