/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.ExecuteSepaDirectDebitParams = factory(root.FinApiResTfulServices.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ExecuteSepaDirectDebitParams model module.
   * @module model/ExecuteSepaDirectDebitParams
   * @version v1.92.0
   */

  /**
   * Constructs a new <code>ExecuteSepaDirectDebitParams</code>.
   * Container for parameters for the execution of a submitted SEPA direct debit order
   * @alias module:model/ExecuteSepaDirectDebitParams
   * @class
   * @param accountId {Number} Identifier of the bank account that you want to transfer money to
   */
  var exports = function(accountId) {
    this.accountId = accountId;
  };

  /**
   * Constructs a <code>ExecuteSepaDirectDebitParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExecuteSepaDirectDebitParams} obj Optional instance to populate.
   * @return {module:model/ExecuteSepaDirectDebitParams} The populated <code>ExecuteSepaDirectDebitParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('accountId'))
        obj.accountId = ApiClient.convertToType(data['accountId'], 'Number');
      if (data.hasOwnProperty('bankingTan'))
        obj.bankingTan = ApiClient.convertToType(data['bankingTan'], 'String');
    }
    return obj;
  }

  /**
   * Identifier of the bank account that you want to transfer money to
   * @member {Number} accountId
   */
  exports.prototype.accountId = undefined;

  /**
   * Banking TAN that the user received from the bank for executing the direct debit order. The field is required if you are licensed to perform SEPA direct debits yourself. Otherwise, i.e. when finAPI's web form flow is required, the web form will deal with executing the service itself.
   * @member {String} bankingTan
   */
  exports.prototype.bankingTan = undefined;

  return exports;

}));
