/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.IbanRuleParams = factory(root.FinApiResTfulServices.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The IbanRuleParams model module.
   * @module model/IbanRuleParams
   * @version v1.92.0
   */

  /**
   * Constructs a new <code>IbanRuleParams</code>.
   * Parameters of IBAN rule
   * @alias module:model/IbanRuleParams
   * @class
   * @param iban {String} IBAN (case-insensitive)
   * @param categoryId {Number} ID of the category that this rule should assign to the matching transactions
   * @param direction {module:model/IbanRuleParams.DirectionEnum} Direction for the rule. 'Income' means that the rule applies to transactions with a positive amount only, 'Spending' means it applies to transactions with a negative amount only. 'Both' means that it applies to both kind of transactions. Note that in case of 'Both', finAPI will create two individual rules (one with direction 'Income' and one with direction 'Spending').
   */
  var exports = function(iban, categoryId, direction) {
    this.iban = iban;
    this.categoryId = categoryId;
    this.direction = direction;
  };

  /**
   * Constructs a <code>IbanRuleParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IbanRuleParams} obj Optional instance to populate.
   * @return {module:model/IbanRuleParams} The populated <code>IbanRuleParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('iban'))
        obj.iban = ApiClient.convertToType(data['iban'], 'String');
      if (data.hasOwnProperty('categoryId'))
        obj.categoryId = ApiClient.convertToType(data['categoryId'], 'Number');
      if (data.hasOwnProperty('direction'))
        obj.direction = ApiClient.convertToType(data['direction'], 'String');
    }
    return obj;
  }

  /**
   * IBAN (case-insensitive)
   * @member {String} iban
   */
  exports.prototype.iban = undefined;

  /**
   * ID of the category that this rule should assign to the matching transactions
   * @member {Number} categoryId
   */
  exports.prototype.categoryId = undefined;

  /**
   * Direction for the rule. 'Income' means that the rule applies to transactions with a positive amount only, 'Spending' means it applies to transactions with a negative amount only. 'Both' means that it applies to both kind of transactions. Note that in case of 'Both', finAPI will create two individual rules (one with direction 'Income' and one with direction 'Spending').
   * @member {module:model/IbanRuleParams.DirectionEnum} direction
   */
  exports.prototype.direction = undefined;


  /**
   * Allowed values for the <code>direction</code> property.
   * @enum {String}
   * @readonly
   */
  exports.DirectionEnum = {
    /**
     * value: "Income"
     * @const
     */
    income: "Income",

    /**
     * value: "Spending"
     * @const
     */
    spending: "Spending",

    /**
     * value: "Both"
     * @const
     */
    both: "Both"
  };

  return exports;

}));
