/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.IbanRuleIdentifiersParams = factory(root.FinApiResTfulServices.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The IbanRuleIdentifiersParams model module.
   * @module model/IbanRuleIdentifiersParams
   * @version v1.92.0
   */

  /**
   * Constructs a new <code>IbanRuleIdentifiersParams</code>.
   * Identifiers params
   * @alias module:model/IbanRuleIdentifiersParams
   * @class
   * @param ids {Array.<Number>} List of identifiers
   */
  var exports = function(ids) {
    this.ids = ids;
  };

  /**
   * Constructs a <code>IbanRuleIdentifiersParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IbanRuleIdentifiersParams} obj Optional instance to populate.
   * @return {module:model/IbanRuleIdentifiersParams} The populated <code>IbanRuleIdentifiersParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('ids'))
        obj.ids = ApiClient.convertToType(data['ids'], ['Number']);
    }
    return obj;
  }

  /**
   * List of identifiers
   * @member {Array.<Number>} ids
   */
  exports.prototype.ids = undefined;

  return exports;

}));
