/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/KeywordRuleParams'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./KeywordRuleParams'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.KeywordRulesParams = factory(root.FinApiResTfulServices.ApiClient, root.FinApiResTfulServices.KeywordRuleParams);
  }
}(this, function(ApiClient, KeywordRuleParams) {
  'use strict';

  /**
   * The KeywordRulesParams model module.
   * @module model/KeywordRulesParams
   * @version v1.92.0
   */

  /**
   * Constructs a new <code>KeywordRulesParams</code>.
   * Params for creation keyword rules
   * @alias module:model/KeywordRulesParams
   * @class
   * @param keywordRules {Array.<module:model/KeywordRuleParams>} Keyword rule definitions. The minimum number of rule definitions is 1. The maximum number of rule definitions is 100.
   */
  var exports = function(keywordRules) {
    this.keywordRules = keywordRules;
  };

  /**
   * Constructs a <code>KeywordRulesParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/KeywordRulesParams} obj Optional instance to populate.
   * @return {module:model/KeywordRulesParams} The populated <code>KeywordRulesParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('keywordRules'))
        obj.keywordRules = ApiClient.convertToType(data['keywordRules'], [KeywordRuleParams]);
    }
    return obj;
  }

  /**
   * Keyword rule definitions. The minimum number of rule definitions is 1. The maximum number of rule definitions is 100.
   * @member {Array.<module:model/KeywordRuleParams>} keywordRules
   */
  exports.prototype.keywordRules = undefined;

  return exports;

}));
