/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MockAccountData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MockAccountData'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.MockBankConnectionUpdate = factory(root.FinApiResTfulServices.ApiClient, root.FinApiResTfulServices.MockAccountData);
  }
}(this, function(ApiClient, MockAccountData) {
  'use strict';

  /**
   * The MockBankConnectionUpdate model module.
   * @module model/MockBankConnectionUpdate
   * @version v1.92.0
   */

  /**
   * Constructs a new <code>MockBankConnectionUpdate</code>.
   * Data for a mock bank connection update
   * @alias module:model/MockBankConnectionUpdate
   * @class
   * @param bankConnectionId {Number} Bank connection identifier
   */
  var exports = function(bankConnectionId) {
    this.bankConnectionId = bankConnectionId;
  };

  /**
   * Constructs a <code>MockBankConnectionUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MockBankConnectionUpdate} obj Optional instance to populate.
   * @return {module:model/MockBankConnectionUpdate} The populated <code>MockBankConnectionUpdate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('bankConnectionId'))
        obj.bankConnectionId = ApiClient.convertToType(data['bankConnectionId'], 'Number');
      if (data.hasOwnProperty('interface'))
        obj._interface = ApiClient.convertToType(data['interface'], 'String');
      if (data.hasOwnProperty('simulateBankLoginError'))
        obj.simulateBankLoginError = ApiClient.convertToType(data['simulateBankLoginError'], 'Boolean');
      if (data.hasOwnProperty('mockAccountsData'))
        obj.mockAccountsData = ApiClient.convertToType(data['mockAccountsData'], [MockAccountData]);
    }
    return obj;
  }

  /**
   * Bank connection identifier
   * @member {Number} bankConnectionId
   */
  exports.prototype.bankConnectionId = undefined;

  /**
   * Banking interface to update. If not specified, then first available interface in bank connection will be used.
   * @member {module:model/MockBankConnectionUpdate.InterfaceEnum} _interface
   */
  exports.prototype._interface = undefined;

  /**
   * Whether to simulate the case that the update fails due to incorrect banking credentials. Note that there is no real communication to any bank server involved, so you won't lock your accounts when enabling this flag. Default value is 'false'.
   * @member {Boolean} simulateBankLoginError
   * @default false
   */
  exports.prototype.simulateBankLoginError = false;

  /**
   * Mock accounts data. Note that for accounts that exist in a bank connection but that you do not specify in this list, the service will act like those accounts are not received by the bank servers. This means that any accounts that you do not specify here will be marked as deprecated. If you do not specify this list at all, all accounts in the bank connection will be marked as deprecated.
   * @member {Array.<module:model/MockAccountData>} mockAccountsData
   */
  exports.prototype.mockAccountsData = undefined;


  /**
   * Allowed values for the <code>_interface</code> property.
   * @enum {String}
   * @readonly
   */
  exports.InterfaceEnum = {
    /**
     * value: "FINTS_SERVER"
     * @const
     */
    FINTS_SERVER: "FINTS_SERVER",

    /**
     * value: "WEB_SCRAPER"
     * @const
     */
    WEB_SCRAPER: "WEB_SCRAPER",

    /**
     * value: "XS2A"
     * @const
     */
    xS2A: "XS2A"
  };

  return exports;

}));
