/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MockBankConnectionUpdate'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MockBankConnectionUpdate'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.MockBatchUpdateParams = factory(root.FinApiResTfulServices.ApiClient, root.FinApiResTfulServices.MockBankConnectionUpdate);
  }
}(this, function(ApiClient, MockBankConnectionUpdate) {
  'use strict';

  /**
   * The MockBatchUpdateParams model module.
   * @module model/MockBatchUpdateParams
   * @version v1.92.0
   */

  /**
   * Constructs a new <code>MockBatchUpdateParams</code>.
   * Data for mock bank connection updates
   * @alias module:model/MockBatchUpdateParams
   * @class
   * @param mockBankConnectionUpdates {Array.<module:model/MockBankConnectionUpdate>} List of mock bank connection updates
   */
  var exports = function(mockBankConnectionUpdates) {
    this.mockBankConnectionUpdates = mockBankConnectionUpdates;
  };

  /**
   * Constructs a <code>MockBatchUpdateParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MockBatchUpdateParams} obj Optional instance to populate.
   * @return {module:model/MockBatchUpdateParams} The populated <code>MockBatchUpdateParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('mockBankConnectionUpdates'))
        obj.mockBankConnectionUpdates = ApiClient.convertToType(data['mockBankConnectionUpdates'], [MockBankConnectionUpdate]);
      if (data.hasOwnProperty('triggerNotifications'))
        obj.triggerNotifications = ApiClient.convertToType(data['triggerNotifications'], 'Boolean');
    }
    return obj;
  }

  /**
   * List of mock bank connection updates
   * @member {Array.<module:model/MockBankConnectionUpdate>} mockBankConnectionUpdates
   */
  exports.prototype.mockBankConnectionUpdates = undefined;

  /**
   * Whether this call should trigger the dispatching of notifications. Default is 'false'.
   * @member {Boolean} triggerNotifications
   * @default false
   */
  exports.prototype.triggerNotifications = false;

  return exports;

}));
