/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.MonthlyUserStats = factory(root.FinApiResTfulServices.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The MonthlyUserStats model module.
   * @module model/MonthlyUserStats
   * @version v1.92.0
   */

  /**
   * Constructs a new <code>MonthlyUserStats</code>.
   * Information about a user's data or activities for a certain month
   * @alias module:model/MonthlyUserStats
   * @class
   * @param month {String} The month that the contained information applies to, in the format 'YYYY-MM'.
   * @param minBankConnectionCount {Number} Minimum count of bank connections that this user has had at any point during the month.
   * @param maxBankConnectionCount {Number} Maximum count of bank connections that this user has had at any point during the month.
   */
  var exports = function(month, minBankConnectionCount, maxBankConnectionCount) {
    this.month = month;
    this.minBankConnectionCount = minBankConnectionCount;
    this.maxBankConnectionCount = maxBankConnectionCount;
  };

  /**
   * Constructs a <code>MonthlyUserStats</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MonthlyUserStats} obj Optional instance to populate.
   * @return {module:model/MonthlyUserStats} The populated <code>MonthlyUserStats</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('month'))
        obj.month = ApiClient.convertToType(data['month'], 'String');
      if (data.hasOwnProperty('minBankConnectionCount'))
        obj.minBankConnectionCount = ApiClient.convertToType(data['minBankConnectionCount'], 'Number');
      if (data.hasOwnProperty('maxBankConnectionCount'))
        obj.maxBankConnectionCount = ApiClient.convertToType(data['maxBankConnectionCount'], 'Number');
    }
    return obj;
  }

  /**
   * The month that the contained information applies to, in the format 'YYYY-MM'.
   * @member {String} month
   */
  exports.prototype.month = undefined;

  /**
   * Minimum count of bank connections that this user has had at any point during the month.
   * @member {Number} minBankConnectionCount
   */
  exports.prototype.minBankConnectionCount = undefined;

  /**
   * Maximum count of bank connections that this user has had at any point during the month.
   * @member {Number} maxBankConnectionCount
   */
  exports.prototype.maxBankConnectionCount = undefined;

  return exports;

}));
