/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.NotificationRule = factory(root.FinApiResTfulServices.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The NotificationRule model module.
   * @module model/NotificationRule
   * @version v1.92.0
   */

  /**
   * Constructs a new <code>NotificationRule</code>.
   * Data of notification rule
   * @alias module:model/NotificationRule
   * @class
   * @param id {Number} Notification rule identifier
   * @param triggerEvent {module:model/NotificationRule.TriggerEventEnum} Trigger event type
   * @param includeDetails {Boolean} Whether the notification messages that will be sent based on this rule contain encrypted detailed data or not
   */
  var exports = function(id, triggerEvent, includeDetails) {
    this.id = id;
    this.triggerEvent = triggerEvent;
    this.includeDetails = includeDetails;
  };

  /**
   * Constructs a <code>NotificationRule</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NotificationRule} obj Optional instance to populate.
   * @return {module:model/NotificationRule} The populated <code>NotificationRule</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('triggerEvent'))
        obj.triggerEvent = ApiClient.convertToType(data['triggerEvent'], 'String');
      if (data.hasOwnProperty('params'))
        obj.params = ApiClient.convertToType(data['params'], {'String': 'String'});
      if (data.hasOwnProperty('callbackHandle'))
        obj.callbackHandle = ApiClient.convertToType(data['callbackHandle'], 'String');
      if (data.hasOwnProperty('includeDetails'))
        obj.includeDetails = ApiClient.convertToType(data['includeDetails'], 'Boolean');
    }
    return obj;
  }

  /**
   * Notification rule identifier
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * Trigger event type
   * @member {module:model/NotificationRule.TriggerEventEnum} triggerEvent
   */
  exports.prototype.triggerEvent = undefined;

  /**
   * Additional parameters that are specific to the trigger event type. Please refer to the documentation for details.
   * @member {Object.<String, String>} params
   */
  exports.prototype.params = undefined;

  /**
   * The string that finAPI includes into the notifications that it sends based on this rule.
   * @member {String} callbackHandle
   */
  exports.prototype.callbackHandle = undefined;

  /**
   * Whether the notification messages that will be sent based on this rule contain encrypted detailed data or not
   * @member {Boolean} includeDetails
   */
  exports.prototype.includeDetails = undefined;


  /**
   * Allowed values for the <code>triggerEvent</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TriggerEventEnum = {
    /**
     * value: "NEW_ACCOUNT_BALANCE"
     * @const
     */
    NEW_ACCOUNT_BALANCE: "NEW_ACCOUNT_BALANCE",

    /**
     * value: "NEW_TRANSACTIONS"
     * @const
     */
    NEW_TRANSACTIONS: "NEW_TRANSACTIONS",

    /**
     * value: "BANK_LOGIN_ERROR"
     * @const
     */
    BANK_LOGIN_ERROR: "BANK_LOGIN_ERROR",

    /**
     * value: "FOREIGN_MONEY_TRANSFER"
     * @const
     */
    FOREIGN_MONEY_TRANSFER: "FOREIGN_MONEY_TRANSFER",

    /**
     * value: "LOW_ACCOUNT_BALANCE"
     * @const
     */
    LOW_ACCOUNT_BALANCE: "LOW_ACCOUNT_BALANCE",

    /**
     * value: "HIGH_TRANSACTION_AMOUNT"
     * @const
     */
    HIGH_TRANSACTION_AMOUNT: "HIGH_TRANSACTION_AMOUNT",

    /**
     * value: "CATEGORY_CASH_FLOW"
     * @const
     */
    CATEGORY_CASH_FLOW: "CATEGORY_CASH_FLOW",

    /**
     * value: "NEW_TERMS_AND_CONDITIONS"
     * @const
     */
    NEW_TERMS_AND_CONDITIONS: "NEW_TERMS_AND_CONDITIONS"
  };

  return exports;

}));
