/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Paging', 'model/Security'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Paging'), require('./Security'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.PageableSecurityList = factory(root.FinApiResTfulServices.ApiClient, root.FinApiResTfulServices.Paging, root.FinApiResTfulServices.Security);
  }
}(this, function(ApiClient, Paging, Security) {
  'use strict';

  /**
   * The PageableSecurityList model module.
   * @module model/PageableSecurityList
   * @version v1.92.0
   */

  /**
   * Constructs a new <code>PageableSecurityList</code>.
   * Container for page of securities
   * @alias module:model/PageableSecurityList
   * @class
   * @param securities {Array.<module:model/Security>} List of securities
   * @param paging {module:model/Paging} Information for pagination
   */
  var exports = function(securities, paging) {
    this.securities = securities;
    this.paging = paging;
  };

  /**
   * Constructs a <code>PageableSecurityList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PageableSecurityList} obj Optional instance to populate.
   * @return {module:model/PageableSecurityList} The populated <code>PageableSecurityList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('securities'))
        obj.securities = ApiClient.convertToType(data['securities'], [Security]);
      if (data.hasOwnProperty('paging'))
        obj.paging = Paging.constructFromObject(data['paging']);
    }
    return obj;
  }

  /**
   * List of securities
   * @member {Array.<module:model/Security>} securities
   */
  exports.prototype.securities = undefined;

  /**
   * Information for pagination
   * @member {module:model/Paging} paging
   */
  exports.prototype.paging = undefined;

  return exports;

}));
