/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Paging', 'model/Transaction'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Paging'), require('./Transaction'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.PageableTransactionList = factory(root.FinApiResTfulServices.ApiClient, root.FinApiResTfulServices.Paging, root.FinApiResTfulServices.Transaction);
  }
}(this, function(ApiClient, Paging, Transaction) {
  'use strict';

  /**
   * The PageableTransactionList model module.
   * @module model/PageableTransactionList
   * @version v1.92.0
   */

  /**
   * Constructs a new <code>PageableTransactionList</code>.
   * Container for a page of transactions, with data about the total count of transactions and their balance
   * @alias module:model/PageableTransactionList
   * @class
   * @param transactions {Array.<module:model/Transaction>} Array of transactions (for the requested page)
   * @param paging {module:model/Paging} Information for pagination
   * @param income {Number} The total income of all transactions (across all pages)
   * @param spending {Number} The total spending of all transactions (across all pages)
   * @param balance {Number} The total sum of all transactions (across all pages)
   */
  var exports = function(transactions, paging, income, spending, balance) {
    this.transactions = transactions;
    this.paging = paging;
    this.income = income;
    this.spending = spending;
    this.balance = balance;
  };

  /**
   * Constructs a <code>PageableTransactionList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PageableTransactionList} obj Optional instance to populate.
   * @return {module:model/PageableTransactionList} The populated <code>PageableTransactionList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('transactions'))
        obj.transactions = ApiClient.convertToType(data['transactions'], [Transaction]);
      if (data.hasOwnProperty('paging'))
        obj.paging = Paging.constructFromObject(data['paging']);
      if (data.hasOwnProperty('income'))
        obj.income = ApiClient.convertToType(data['income'], 'Number');
      if (data.hasOwnProperty('spending'))
        obj.spending = ApiClient.convertToType(data['spending'], 'Number');
      if (data.hasOwnProperty('balance'))
        obj.balance = ApiClient.convertToType(data['balance'], 'Number');
    }
    return obj;
  }

  /**
   * Array of transactions (for the requested page)
   * @member {Array.<module:model/Transaction>} transactions
   */
  exports.prototype.transactions = undefined;

  /**
   * Information for pagination
   * @member {module:model/Paging} paging
   */
  exports.prototype.paging = undefined;

  /**
   * The total income of all transactions (across all pages)
   * @member {Number} income
   */
  exports.prototype.income = undefined;

  /**
   * The total spending of all transactions (across all pages)
   * @member {Number} spending
   */
  exports.prototype.spending = undefined;

  /**
   * The total sum of all transactions (across all pages)
   * @member {Number} balance
   */
  exports.prototype.balance = undefined;

  return exports;

}));
