/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.SingleMoneyTransferRecipientData = factory(root.FinApiResTfulServices.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The SingleMoneyTransferRecipientData model module.
   * @module model/SingleMoneyTransferRecipientData
   * @version v1.92.0
   */

  /**
   * Constructs a new <code>SingleMoneyTransferRecipientData</code>.
   * Recipient data for a single money transfer order
   * @alias module:model/SingleMoneyTransferRecipientData
   * @class
   * @param amount {Number} The amount to transfer. Must be a positive decimal number with at most two decimal places (e.g. 99.99)
   */
  var exports = function(amount) {
    this.amount = amount;
  };

  /**
   * Constructs a <code>SingleMoneyTransferRecipientData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SingleMoneyTransferRecipientData} obj Optional instance to populate.
   * @return {module:model/SingleMoneyTransferRecipientData} The populated <code>SingleMoneyTransferRecipientData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('recipientName'))
        obj.recipientName = ApiClient.convertToType(data['recipientName'], 'String');
      if (data.hasOwnProperty('recipientIban'))
        obj.recipientIban = ApiClient.convertToType(data['recipientIban'], 'String');
      if (data.hasOwnProperty('recipientBic'))
        obj.recipientBic = ApiClient.convertToType(data['recipientBic'], 'String');
      if (data.hasOwnProperty('clearingAccountId'))
        obj.clearingAccountId = ApiClient.convertToType(data['clearingAccountId'], 'String');
      if (data.hasOwnProperty('endToEndId'))
        obj.endToEndId = ApiClient.convertToType(data['endToEndId'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('purpose'))
        obj.purpose = ApiClient.convertToType(data['purpose'], 'String');
      if (data.hasOwnProperty('sepaPurposeCode'))
        obj.sepaPurposeCode = ApiClient.convertToType(data['sepaPurposeCode'], 'String');
    }
    return obj;
  }

  /**
   * Name of the recipient. Note: Neither finAPI nor the involved bank servers are guaranteed to validate the recipient name. Even if the recipient name does not depict the actual registered account holder of the specified recipient account, the money transfer request might still be successful. This field is optional only when you pass a clearing account as the recipient. Otherwise, this field is required.
   * @member {String} recipientName
   */
  exports.prototype.recipientName = undefined;

  /**
   * IBAN of the recipient's account. This field is optional only when you pass a clearing account as the recipient. Otherwise, this field is required.
   * @member {String} recipientIban
   */
  exports.prototype.recipientIban = undefined;

  /**
   * BIC of the recipient's account. Note: This field is optional when you pass a clearing account as the recipient or if the bank connection of the account that you want to transfer money from supports the IBAN-Only money transfer. You can find this out via GET /bankConnections/<id>. If no BIC is given, finAPI will try to recognize it using the given recipientIban value (if it's given). And then if the result value is not empty, it will be used for the money transfer request independent of whether it is required or not (unless you pass a clearing account, in which case the value will always be ignored).
   * @member {String} recipientBic
   */
  exports.prototype.recipientBic = undefined;

  /**
   * Identifier of a clearing account. If this field is set, then the fields 'recipientName', 'recipientIban' and 'recipientBic' will be ignored and the recipient account will be the specified clearing account.
   * @member {String} clearingAccountId
   */
  exports.prototype.clearingAccountId = undefined;

  /**
   * End-To-End ID for the transfer transaction
   * @member {String} endToEndId
   */
  exports.prototype.endToEndId = undefined;

  /**
   * The amount to transfer. Must be a positive decimal number with at most two decimal places (e.g. 99.99)
   * @member {Number} amount
   */
  exports.prototype.amount = undefined;

  /**
   * The purpose of the transfer transaction
   * @member {String} purpose
   */
  exports.prototype.purpose = undefined;

  /**
   * SEPA purpose code, according to ISO 20022, external codes set.
   * @member {String} sepaPurposeCode
   */
  exports.prototype.sepaPurposeCode = undefined;

  return exports;

}));
