/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.SingleDirectDebitData = factory(root.FinApiResTfulServices.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The SingleDirectDebitData model module.
   * @module model/SingleDirectDebitData
   * @version v1.92.0
   */

  /**
   * Constructs a new <code>SingleDirectDebitData</code>.
   * Data for a single direct debit
   * @alias module:model/SingleDirectDebitData
   * @class
   * @param debitorName {String} Name of the debitor. Note: Neither finAPI nor the involved bank servers are guaranteed to validate the debitor name. Even if the debitor name does not depict the actual registered account holder of the specified debitor account, the direct debit request might still be successful.
   * @param debitorIban {String} IBAN of the debitor's account
   * @param amount {Number} The amount to transfer. Must be a positive decimal number with at most two decimal places (e.g. 99.99)
   * @param mandateId {String} Mandate ID that this direct debit order is based on.
   * @param mandateDate {String} Date of the mandate that this direct debit order is based on, in the format 'YYYY-MM-DD'
   */
  var exports = function(debitorName, debitorIban, amount, mandateId, mandateDate) {
    this.debitorName = debitorName;
    this.debitorIban = debitorIban;
    this.amount = amount;
    this.mandateId = mandateId;
    this.mandateDate = mandateDate;
  };

  /**
   * Constructs a <code>SingleDirectDebitData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SingleDirectDebitData} obj Optional instance to populate.
   * @return {module:model/SingleDirectDebitData} The populated <code>SingleDirectDebitData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('debitorName'))
        obj.debitorName = ApiClient.convertToType(data['debitorName'], 'String');
      if (data.hasOwnProperty('debitorIban'))
        obj.debitorIban = ApiClient.convertToType(data['debitorIban'], 'String');
      if (data.hasOwnProperty('debitorBic'))
        obj.debitorBic = ApiClient.convertToType(data['debitorBic'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('purpose'))
        obj.purpose = ApiClient.convertToType(data['purpose'], 'String');
      if (data.hasOwnProperty('sepaPurposeCode'))
        obj.sepaPurposeCode = ApiClient.convertToType(data['sepaPurposeCode'], 'String');
      if (data.hasOwnProperty('mandateId'))
        obj.mandateId = ApiClient.convertToType(data['mandateId'], 'String');
      if (data.hasOwnProperty('mandateDate'))
        obj.mandateDate = ApiClient.convertToType(data['mandateDate'], 'String');
      if (data.hasOwnProperty('creditorId'))
        obj.creditorId = ApiClient.convertToType(data['creditorId'], 'String');
      if (data.hasOwnProperty('endToEndId'))
        obj.endToEndId = ApiClient.convertToType(data['endToEndId'], 'String');
    }
    return obj;
  }

  /**
   * Name of the debitor. Note: Neither finAPI nor the involved bank servers are guaranteed to validate the debitor name. Even if the debitor name does not depict the actual registered account holder of the specified debitor account, the direct debit request might still be successful.
   * @member {String} debitorName
   */
  exports.prototype.debitorName = undefined;

  /**
   * IBAN of the debitor's account
   * @member {String} debitorIban
   */
  exports.prototype.debitorIban = undefined;

  /**
   * BIC of the debitor's account. Note: This field is optional if - and only if - the bank connection of the account that you want to transfer money to supports the IBAN-Only direct debit. You can find this out via GET /bankConnections/<id>. If no BIC is given, finAPI will try to recognize it using the given debitorIban value (if it's given). And then if the result value is not empty, it will be used for the direct debit request independent of whether it is required or not.
   * @member {String} debitorBic
   */
  exports.prototype.debitorBic = undefined;

  /**
   * The amount to transfer. Must be a positive decimal number with at most two decimal places (e.g. 99.99)
   * @member {Number} amount
   */
  exports.prototype.amount = undefined;

  /**
   * The purpose of the transfer transaction
   * @member {String} purpose
   */
  exports.prototype.purpose = undefined;

  /**
   * SEPA purpose code, according to ISO 20022, external codes set.
   * @member {String} sepaPurposeCode
   */
  exports.prototype.sepaPurposeCode = undefined;

  /**
   * Mandate ID that this direct debit order is based on.
   * @member {String} mandateId
   */
  exports.prototype.mandateId = undefined;

  /**
   * Date of the mandate that this direct debit order is based on, in the format 'YYYY-MM-DD'
   * @member {String} mandateDate
   */
  exports.prototype.mandateDate = undefined;

  /**
   * Creditor ID of the source account's holder
   * @member {String} creditorId
   */
  exports.prototype.creditorId = undefined;

  /**
   * End-To-End ID for the transfer transaction
   * @member {String} endToEndId
   */
  exports.prototype.endToEndId = undefined;

  return exports;

}));
