/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AccountReference', 'model/LoginCredential', 'model/MultiStepAuthenticationCallback'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AccountReference'), require('./LoginCredential'), require('./MultiStepAuthenticationCallback'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.UpdateBankConnectionParams = factory(root.FinApiResTfulServices.ApiClient, root.FinApiResTfulServices.AccountReference, root.FinApiResTfulServices.LoginCredential, root.FinApiResTfulServices.MultiStepAuthenticationCallback);
  }
}(this, function(ApiClient, AccountReference, LoginCredential, MultiStepAuthenticationCallback) {
  'use strict';

  /**
   * The UpdateBankConnectionParams model module.
   * @module model/UpdateBankConnectionParams
   * @version v1.92.0
   */

  /**
   * Constructs a new <code>UpdateBankConnectionParams</code>.
   * Container for bank connection update parameters
   * @alias module:model/UpdateBankConnectionParams
   * @class
   * @param bankConnectionId {Number} Bank connection identifier
   */
  var exports = function(bankConnectionId) {
    this.bankConnectionId = bankConnectionId;
  };

  /**
   * Constructs a <code>UpdateBankConnectionParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateBankConnectionParams} obj Optional instance to populate.
   * @return {module:model/UpdateBankConnectionParams} The populated <code>UpdateBankConnectionParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('bankConnectionId'))
        obj.bankConnectionId = ApiClient.convertToType(data['bankConnectionId'], 'Number');
      if (data.hasOwnProperty('bankingPin'))
        obj.bankingPin = ApiClient.convertToType(data['bankingPin'], 'String');
      if (data.hasOwnProperty('storePin'))
        obj.storePin = ApiClient.convertToType(data['storePin'], 'Boolean');
      if (data.hasOwnProperty('interface'))
        obj._interface = ApiClient.convertToType(data['interface'], 'String');
      if (data.hasOwnProperty('loginCredentials'))
        obj.loginCredentials = ApiClient.convertToType(data['loginCredentials'], [LoginCredential]);
      if (data.hasOwnProperty('storeSecrets'))
        obj.storeSecrets = ApiClient.convertToType(data['storeSecrets'], 'Boolean');
      if (data.hasOwnProperty('importNewAccounts'))
        obj.importNewAccounts = ApiClient.convertToType(data['importNewAccounts'], 'Boolean');
      if (data.hasOwnProperty('skipPositionsDownload'))
        obj.skipPositionsDownload = ApiClient.convertToType(data['skipPositionsDownload'], 'Boolean');
      if (data.hasOwnProperty('loadOwnerData'))
        obj.loadOwnerData = ApiClient.convertToType(data['loadOwnerData'], 'Boolean');
      if (data.hasOwnProperty('accountReferences'))
        obj.accountReferences = ApiClient.convertToType(data['accountReferences'], [AccountReference]);
      if (data.hasOwnProperty('challengeResponse'))
        obj.challengeResponse = ApiClient.convertToType(data['challengeResponse'], 'String');
      if (data.hasOwnProperty('multiStepAuthentication'))
        obj.multiStepAuthentication = MultiStepAuthenticationCallback.constructFromObject(data['multiStepAuthentication']);
      if (data.hasOwnProperty('redirectUrl'))
        obj.redirectUrl = ApiClient.convertToType(data['redirectUrl'], 'String');
    }
    return obj;
  }

  /**
   * Bank connection identifier
   * @member {Number} bankConnectionId
   */
  exports.prototype.bankConnectionId = undefined;

  /**
   * NOTE: This field is deprecated and will be removed at some point. Use 'loginCredentials' + 'interface' instead. If any of those two fields is used, then the value of this field will be ignored.<br><br>Online banking PIN. Any symbols are allowed. Max length: 170. If a PIN is stored in the bank connection, then this field may remain unset. If finAPI's web form is not required and the field is set though then it will always be used (even if there is some other PIN stored in the bank connection). If you want the user to enter a PIN in finAPI's web form even when a PIN is stored, then just set the field to any value, so that the service recognizes that you wish to use the web form flow.
   * @member {String} bankingPin
   */
  exports.prototype.bankingPin = undefined;

  /**
   * NOTE: This field is deprecated and will be removed at some point. Use 'storeSecrets' instead.<br><br>Whether to store the PIN. If the PIN is stored, it is not required to pass the PIN again when updating this bank connection or when executing orders (like money transfers). Default is false. <br/><br/>NOTES:<br/> - before you set this field to true, please regard the 'pinsAreVolatile' flag of this connection's bank;<br/> - this field is ignored in case when the user will need to use finAPI's web form. The user will be able to decide whether to store the PIN or not in the web form, depending on the 'storeSecretsAvailableInWebForm' setting (see Client Configuration).
   * @member {Boolean} storePin
   * @default false
   */
  exports.prototype.storePin = false;

  /**
   * The interface to use for connecting with the bank.
   * @member {module:model/UpdateBankConnectionParams.InterfaceEnum} _interface
   */
  exports.prototype._interface = undefined;

  /**
   * Set of login credentials. Must be passed in combination with the 'interface' field. The labels that you pass must match with the login credential labels that the respective interface defines. finAPI will combine the given credentials with any credentials that it has stored. You can leave this field unset in case finAPI has stored all required credentials. When you must use a web form, you can also leave this field unset and the web form will take care of getting the credentials from the user. However, if you do pass credentials in that case, the web form will show only those fields that you have given.
   * @member {Array.<module:model/LoginCredential>} loginCredentials
   */
  exports.prototype.loginCredentials = undefined;

  /**
   * Whether to store the secret login fields. If the secret fields are stored, then updates can be triggered without the involvement of the users, as long as the credentials remain valid and the bank consent has not expired. Note that bank consent will be stored regardless of the field value. Default value is false.<br/><br/>NOTES:<br/> - this field is ignored in case when the user will need to use finAPI's web form. The user will be able to decide whether to store the secrets or not in the web form, depending on the 'storeSecretsAvailableInWebForm' setting (see Client Configuration).
   * @member {Boolean} storeSecrets
   * @default false
   */
  exports.prototype.storeSecrets = false;

  /**
   * Whether new accounts that have not yet been imported will be imported or not. Default is false. <br/><br/>NOTES:<br/>&bull; For best performance of the bank connection update, you should not enable this flag unless you really expect new accounts to be available in the connection. It is recommended to let your users tell you through your application when they want the service to look for new accounts.<br/>&bull; If you have imported a bank connection using specific <code>accountTypeIds</code> (e.g. <code>1,2</code> to import checking and saving accounts), you would import all other accounts (e.g. security accounts or credit cards) by setting <code>importNewAccounts</code> to <code>true</code>. To avoid importing account types that you are not interested in, make sure this field is undefined or set to false.
   * @member {Boolean} importNewAccounts
   * @default false
   */
  exports.prototype.importNewAccounts = false;

  /**
   * Whether to skip the download of transactions and securities or not. If set to true, then finAPI will download just the accounts list with the accounts' information (like account name, number, holder, etc), as well as the accounts' balances (if possible), but skip the download of transactions and securities. Default is false.<br/><br/>NOTES:<br/>&bull; If you skip the download of transactions and securities during an import or update, you can still download them on a later update (though you might not get all positions at a later point, because the date range in which the bank servers provide this data is usually limited). However, once finAPI has downloaded the transactions or securities for the first time, you will not be able to go back to skipping the download of transactions and securities! In other words: Once you make your first request with <code>skipPositionsDownload=false</code> for a certain bank connection, you will no longer be able to make a request with <code>skipPositionsDownload=true</code> for that same bank connection.<br/>&bull; If this bank connection is updated via finAPI's automatic batch update, then transactions and security positions <u>will</u> be downloaded in any case!<br/>&bull; For security accounts, skipping the downloading of the securities might result in the account's balance also not being downloaded.<br/>
   * @member {Boolean} skipPositionsDownload
   * @default false
   */
  exports.prototype.skipPositionsDownload = false;

  /**
   * Whether to load/refresh information about the bank connection owner(s) - see field 'owners'. Default value is 'false'. Note that owner data is NOT loaded/refreshed during finAPI's automatic bank connection update.
   * @member {Boolean} loadOwnerData
   * @default false
   */
  exports.prototype.loadOwnerData = false;

  /**
   * List of accounts for which access is requested from the bank. It may only be passed if the bank interface has the DETAILED_CONSENT property set. if omitted, finAPI will use the list of existing accounts. Note that the parameter is still required if you want to import new accounts (i.e. call with importNewAccounts=true).
   * @member {Array.<module:model/AccountReference>} accountReferences
   */
  exports.prototype.accountReferences = undefined;

  /**
   * NOTE: This field is DEPRECATED and will get removed at some point. Please refer to the 'multiStepAuthentication' field instead.<br/><br/>Challenge response. This field should be set only when the previous attempt of update the bank connection failed with HTTP code 510, i.e. the bank sent a challenge for the user for an additional authentication. In this case, this field must contain the response to the bank's challenge. Note that in the context of finAPI's web form flow, finAPI will automatically deal with getting the challenge response from the user via the web form.
   * @member {String} challengeResponse
   */
  exports.prototype.challengeResponse = undefined;

  /**
   * Container for multi-step authentication data. Required when a previous service call initiated a multi-step authentication.
   * @member {module:model/MultiStepAuthenticationCallback} multiStepAuthentication
   */
  exports.prototype.multiStepAuthentication = undefined;

  /**
   * Must only be passed when the used interface has the property REDIRECT_APPROACH and no web form flow is used. The user will be redirected to the given URL from the bank's website after having entered his credentials. Must use HTTPS protocol.
   * @member {String} redirectUrl
   */
  exports.prototype.redirectUrl = undefined;


  /**
   * Allowed values for the <code>_interface</code> property.
   * @enum {String}
   * @readonly
   */
  exports.InterfaceEnum = {
    /**
     * value: "FINTS_SERVER"
     * @const
     */
    FINTS_SERVER: "FINTS_SERVER",

    /**
     * value: "WEB_SCRAPER"
     * @const
     */
    WEB_SCRAPER: "WEB_SCRAPER",

    /**
     * value: "XS2A"
     * @const
     */
    xS2A: "XS2A"
  };

  return exports;

}));
