/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.UserIdentifiersList = factory(root.FinApiResTfulServices.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The UserIdentifiersList model module.
   * @module model/UserIdentifiersList
   * @version v1.92.0
   */

  /**
   * Constructs a new <code>UserIdentifiersList</code>.
   * Container for list of identifiers of deleted users, and not deleted users (in ascending order)
   * @alias module:model/UserIdentifiersList
   * @class
   * @param deletedUsers {Array.<String>} List of identifiers of deleted users (in ascending order)
   * @param nonDeletedUsers {Array.<String>} List of identifiers of not deleted users (in ascending order)
   */
  var exports = function(deletedUsers, nonDeletedUsers) {
    this.deletedUsers = deletedUsers;
    this.nonDeletedUsers = nonDeletedUsers;
  };

  /**
   * Constructs a <code>UserIdentifiersList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserIdentifiersList} obj Optional instance to populate.
   * @return {module:model/UserIdentifiersList} The populated <code>UserIdentifiersList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('deletedUsers'))
        obj.deletedUsers = ApiClient.convertToType(data['deletedUsers'], ['String']);
      if (data.hasOwnProperty('nonDeletedUsers'))
        obj.nonDeletedUsers = ApiClient.convertToType(data['nonDeletedUsers'], ['String']);
    }
    return obj;
  }

  /**
   * List of identifiers of deleted users (in ascending order)
   * @member {Array.<String>} deletedUsers
   */
  exports.prototype.deletedUsers = undefined;

  /**
   * List of identifiers of not deleted users (in ascending order)
   * @member {Array.<String>} nonDeletedUsers
   */
  exports.prototype.nonDeletedUsers = undefined;

  return exports;

}));
