/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BadCredentialsError', 'model/ClientConfiguration', 'model/ClientConfigurationParams', 'model/ErrorMessage'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/BadCredentialsError'), require('../model/ClientConfiguration'), require('../model/ClientConfigurationParams'), require('../model/ErrorMessage'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.ClientConfigurationApi = factory(root.FinApiResTfulServices.ApiClient, root.FinApiResTfulServices.BadCredentialsError, root.FinApiResTfulServices.ClientConfiguration, root.FinApiResTfulServices.ClientConfigurationParams, root.FinApiResTfulServices.ErrorMessage);
  }
}(this, function(ApiClient, BadCredentialsError, ClientConfiguration, ClientConfigurationParams, ErrorMessage) {
  'use strict';

  /**
   * ClientConfiguration service.
   * @module api/ClientConfigurationApi
   * @version v1.92.0
   */

  /**
   * Constructs a new ClientConfigurationApi. 
   * @alias module:api/ClientConfigurationApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the editClientConfiguration operation.
     * @callback module:api/ClientConfigurationApi~editClientConfigurationCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ClientConfiguration} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Edit client configuration
     * Edit your client's configuration. Must pass your global (i.e. client) access_token.<br/><br/> <b>NOTE</b>: When token validity periods are changed, this only applies to newly requested tokens, and does not change the expiration time of already existing tokens.
     * @param {Object} opts Optional parameters
     * @param {module:model/ClientConfigurationParams} opts.body Client configuration parameters
     * @param {module:api/ClientConfigurationApi~editClientConfigurationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ClientConfiguration}
     */
    this.editClientConfiguration = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['finapi_auth'];
      var contentTypes = [];
      var accepts = [];
      var returnType = ClientConfiguration;

      return this.apiClient.callApi(
        '/api/v1/clientConfiguration', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getClientConfiguration operation.
     * @callback module:api/ClientConfigurationApi~getClientConfigurationCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ClientConfiguration} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get client configuration
     * Get your client's configuration. Must pass your global (i.e. client) access_token.
     * @param {module:api/ClientConfigurationApi~getClientConfigurationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ClientConfiguration}
     */
    this.getClientConfiguration = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['finapi_auth'];
      var contentTypes = [];
      var accepts = [];
      var returnType = ClientConfiguration;

      return this.apiClient.callApi(
        '/api/v1/clientConfiguration', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
