/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BadCredentialsError', 'model/ErrorMessage', 'model/IdentifierList', 'model/PageableTransactionList', 'model/SplitTransactionsParams', 'model/Transaction', 'model/TransactionList', 'model/TriggerCategorizationParams', 'model/UpdateMultipleTransactionsParams', 'model/UpdateTransactionsParams'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/BadCredentialsError'), require('../model/ErrorMessage'), require('../model/IdentifierList'), require('../model/PageableTransactionList'), require('../model/SplitTransactionsParams'), require('../model/Transaction'), require('../model/TransactionList'), require('../model/TriggerCategorizationParams'), require('../model/UpdateMultipleTransactionsParams'), require('../model/UpdateTransactionsParams'));
  } else {
    // Browser globals (root is window)
    if (!root.FinApiResTfulServices) {
      root.FinApiResTfulServices = {};
    }
    root.FinApiResTfulServices.TransactionsApi = factory(root.FinApiResTfulServices.ApiClient, root.FinApiResTfulServices.BadCredentialsError, root.FinApiResTfulServices.ErrorMessage, root.FinApiResTfulServices.IdentifierList, root.FinApiResTfulServices.PageableTransactionList, root.FinApiResTfulServices.SplitTransactionsParams, root.FinApiResTfulServices.Transaction, root.FinApiResTfulServices.TransactionList, root.FinApiResTfulServices.TriggerCategorizationParams, root.FinApiResTfulServices.UpdateMultipleTransactionsParams, root.FinApiResTfulServices.UpdateTransactionsParams);
  }
}(this, function(ApiClient, BadCredentialsError, ErrorMessage, IdentifierList, PageableTransactionList, SplitTransactionsParams, Transaction, TransactionList, TriggerCategorizationParams, UpdateMultipleTransactionsParams, UpdateTransactionsParams) {
  'use strict';

  /**
   * Transactions service.
   * @module api/TransactionsApi
   * @version v1.92.0
   */

  /**
   * Constructs a new TransactionsApi. 
   * @alias module:api/TransactionsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the deleteAllTransactions operation.
     * @callback module:api/TransactionsApi~deleteAllTransactionsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/IdentifierList} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete all transactions
     * Delete a set, or the entirety, of transactions of the currently authorized user.
     * @param {Object} opts Optional parameters
     * @param {String} opts.maxDeletionDate If specified, then only those transactions are being deleted whose 'finapiBookingDate' is equal to or earlier to the given date. The date may not be in future, and must be given in the format 'YYYY-MM-DD'. If not specified, then no date limitation will be in place for the deletion.
     * @param {Boolean} opts.safeMode When passing 'true', then only those transactions are being deleted where at least one of the following holds true: 1. The transaction belongs to a 'demo connection'; 2. The transaction's 'potentialDuplicate' flag is set to TRUE; 3. The transaction is an adjusting entry ('Zwischensaldo' transaction) that was added by finAPI. When passing 'false', then finAPI will delete transactions independent of these characteristics. The default value for this parameter is 'true'. (default to true)
     * @param {Boolean} opts.rememberDeletion When passing 'true', then finAPI will make sure to not re-import deleted transactions on future account updates. When 'false', then deleted transactions might be re-imported. Default value for this parameter is 'false'. (default to false)
     * @param {module:api/TransactionsApi~deleteAllTransactionsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/IdentifierList}
     */
    this.deleteAllTransactions = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'maxDeletionDate': opts['maxDeletionDate'],
        'safeMode': opts['safeMode'],
        'rememberDeletion': opts['rememberDeletion'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['finapi_auth'];
      var contentTypes = [];
      var accepts = [];
      var returnType = IdentifierList;

      return this.apiClient.callApi(
        '/api/v1/transactions', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteTransaction operation.
     * @callback module:api/TransactionsApi~deleteTransactionCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a transaction
     * Delete a single transaction of the user that is authorized by the access_token.<br/><br/> A transaction can only get deleted if at least one of the following holds true:<br/> &bull; The transaction belongs to a 'demo connection'<br/> &bull; The transaction's 'potentialDuplicate' flag is set to TRUE<br/> &bull; The transaction is an adjusting entry ('Zwischensaldo' transaction) that was added by finAPI<br/><br/>Note that the 'Delete all transactions' service has additional functionality and allows you to delete transactions that you cannot delete with this service.
     * @param {Number} id Identifier of transaction
     * @param {module:api/TransactionsApi~deleteTransactionCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteTransaction = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteTransaction");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['finapi_auth'];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/transactions/{id}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the editMultipleTransactions operation.
     * @callback module:api/TransactionsApi~editMultipleTransactionsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/IdentifierList} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Edit multiple transactions
     * Edit one or multiple transactions. You can edit the following fields: 'isNew=true|false' and/or 'isPotentialDuplicate=false' and/or 'categoryId=<id>' and/or 'labelIds=[<ids>]'. To clear the category of the given transactions (so that they are no longer categorized), pass the value '0' as the categoryId. To clear the labels of the given transactions, pass an empty array of label identifiers: '[]'. The parameters 'categoryId' and 'labelIds' are forbidden if 'ids' is NOT set (i.e. you cannot update the category or labels for ALL transactions). The result is a list of identifiers of only those transactions that have changed as a result of this service call.
     * @param {module:model/UpdateMultipleTransactionsParams} body Update transactions parameters
     * @param {module:api/TransactionsApi~editMultipleTransactionsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/IdentifierList}
     */
    this.editMultipleTransactions = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling editMultipleTransactions");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['finapi_auth'];
      var contentTypes = [];
      var accepts = [];
      var returnType = IdentifierList;

      return this.apiClient.callApi(
        '/api/v1/transactions', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the editMultipleTransactionsDeprecated operation.
     * @callback module:api/TransactionsApi~editMultipleTransactionsDeprecatedCallback
     * @param {String} error Error message, if any.
     * @param {module:model/IdentifierList} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Edit multiple transactions (DEPRECATED)
     * Change the fields of multiple transactions. You can change the following fields: 'isNew=true|false' and/or 'isPotentialDuplicate=false' and/or 'categoryId=<id>' and/or 'labelIds=[<ids>]'. The max number of input identifiers is limited to 100. To clear the category of the given transactions (so that they are no longer categorized), pass the value '0' as the categoryId. To clear the labels of the given transactions, pass an empty array of label identifiers: '[]'. The result is a list of identifiers of only those transactions that have changed as a result of this service call. WARNING: This service is deprecated and will be removed at some point. If you want to edit multiple transactions, please instead use the service 'Edit multiple transactions', where you can pass a comma-separated list of identifiers.
     * @param {Array.<Number>} ids Comma-separated list of identifiers of updated transactions
     * @param {module:model/UpdateTransactionsParams} body Update transactions parameters
     * @param {module:api/TransactionsApi~editMultipleTransactionsDeprecatedCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/IdentifierList}
     */
    this.editMultipleTransactionsDeprecated = function(ids, body, callback) {
      var postBody = body;

      // verify the required parameter 'ids' is set
      if (ids === undefined || ids === null) {
        throw new Error("Missing the required parameter 'ids' when calling editMultipleTransactionsDeprecated");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling editMultipleTransactionsDeprecated");
      }


      var pathParams = {
        'ids': ids
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['finapi_auth'];
      var contentTypes = [];
      var accepts = [];
      var returnType = IdentifierList;

      return this.apiClient.callApi(
        '/api/v1/transactions/{ids}', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the editTransaction operation.
     * @callback module:api/TransactionsApi~editTransactionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Transaction} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Edit a transaction
     * Change a transaction's fields. You can change the following fields: 'isNew=true|false' and/or 'isPotentialDuplicate=false' and/or 'categoryId=<id>' and/or 'labelIds=[<ids>]'. To clear a transaction's category (so that it is no longer categorized), pass the value '0' as the categoryId. To clear the labels of the given transaction, pass an empty array of label identifiers: '[]'.
     * @param {Number} id Identifier of transaction
     * @param {module:model/UpdateTransactionsParams} body Update transactions parameters
     * @param {module:api/TransactionsApi~editTransactionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Transaction}
     */
    this.editTransaction = function(id, body, callback) {
      var postBody = body;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling editTransaction");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling editTransaction");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['finapi_auth'];
      var contentTypes = [];
      var accepts = [];
      var returnType = Transaction;

      return this.apiClient.callApi(
        '/api/v1/transactions/{id}', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getAndSearchAllTransactions operation.
     * @callback module:api/TransactionsApi~getAndSearchAllTransactionsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PageableTransactionList} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get and search all transactions
     * Get transactions of the user that is authorized by the access_token. Must pass the user's access_token. You can set optional search criteria to get only those transactions that you are interested in. If you do not specify any search criteria, then this service functions as a 'get all' service.
     * @param {module:model/String} view This parameter defines finAPI's logical view on the transactions when querying them: 'bankView' regards only the original transactions as they were received from the bank, without considering how the transactions might have gotten split by the user (see POST /transactions/<id>/split). This means that if a transaction is split into logical sub-transactions, then the service will still regard only the original transaction, and NOT the logical sub-transactions in its processing (though for convenience, the transactions will have the data of their sub-transactions included in the response). 'userView' by contrast regards the transactions as they exist for the user. For transactions that have not been split into logical sub-transactions, there is no difference to the \"bankView\". But for transaction that have been split into logical sub-transactions, the service will ONLY regard these sub-transactions, and not the originally received transaction (though for convenience, the sub-transactions will have the identifier of their original transaction included in the response).
     * @param {Object} opts Optional parameters
     * @param {Array.<Number>} opts.ids A comma-separated list of transaction identifiers. If specified, then only transactions whose identifier match any of the given identifiers will be regarded. The maximum number of identifiers is 1000.
     * @param {String} opts.search If specified, then only those transactions will be contained in the result whose 'purpose' or counterpart fields contain the given search string (the matching works case-insensitive). If no transactions contain the search string in any of these fields, then the result will be an empty list. NOTE: If the given search string consists of several terms (separated by whitespace), then ALL of these terms must be contained in the searched fields in order for a transaction to get included into the result.
     * @param {String} opts.counterpart If specified, then only those transactions will be contained in the result whose counterpart fields contain the given search string (the matching works case-insensitive). If no transactions contain the search string in any of the counterpart fields, then the result will be an empty list. NOTE: If the given search string consists of several terms (separated by whitespace), then ALL of these terms must be contained in the searched fields in order for a transaction to get included into the result.
     * @param {String} opts.purpose If specified, then only those transactions will be contained in the result whose purpose field contains the given search string (the matching works case-insensitive). If no transactions contain the search string in the purpose field, then the result will be an empty list. NOTE: If the given search string consists of several terms (separated by whitespace), then ALL of these terms must be contained in the purpose in order for a transaction to get included into the result.
     * @param {Array.<Number>} opts.accountIds A comma-separated list of account identifiers. If specified, then only transactions that relate to the given accounts will be regarded. If not specified, then all accounts will be regarded.
     * @param {String} opts.minBankBookingDate Lower bound for a transaction's booking date as returned by the bank (= original booking date), in the format 'YYYY-MM-DD' (e.g. '2016-01-01'). If specified, then only transactions whose 'bankBookingDate' is equal to or later than the given date will be regarded.
     * @param {String} opts.maxBankBookingDate Upper bound for a transaction's booking date as returned by the bank (= original booking date), in the format 'YYYY-MM-DD' (e.g. '2016-01-01'). If specified, then only transactions whose 'bankBookingDate' is equal to or earlier than the given date will be regarded.
     * @param {String} opts.minFinapiBookingDate Lower bound for a transaction's booking date as set by finAPI, in the format 'YYYY-MM-DD' (e.g. '2016-01-01'). For details about the meaning of the finAPI booking date, please see the field's documentation in the service's response.
     * @param {String} opts.maxFinapiBookingDate Upper bound for a transaction's booking date as set by finAPI, in the format 'YYYY-MM-DD' (e.g. '2016-01-01'). For details about the meaning of the finAPI booking date, please see the field's documentation in the service's response.
     * @param {Number} opts.minAmount If specified, then only transactions whose amount is equal to or greater than the given amount will be regarded. Can contain a positive or negative number with at most two decimal places. Examples: -300.12, or 90.95
     * @param {Number} opts.maxAmount If specified, then only transactions whose amount is equal to or less than the given amount will be regarded. Can contain a positive or negative number with at most two decimal places. Examples: -300.12, or 90.95
     * @param {module:model/String} opts.direction If specified, then only transactions with the given direction(s) will be regarded. Use 'income' for regarding only received payments (amount >= 0), 'spending' for regarding only outgoing payments (amount < 0), or 'all' to regard both directions. If not specified, the direction defaults to 'all'. (default to all)
     * @param {Array.<Number>} opts.labelIds A comma-separated list of label identifiers. If specified, then only transactions that have been marked with at least one of the given labels will be contained in the result.
     * @param {Array.<Number>} opts.categoryIds A comma-separated list of category identifiers. If specified, then the result will contain only transactions whose category is either one of the given categories, or - but only if the 'includeChildCategories' flag is set to 'true' - whose category is a sub-category of one of the given categories. To include transactions without any category, pass the value '0' as the categoryId.
     * @param {Boolean} opts.includeChildCategories This flag controls how the given 'categoryIds' are handled. If set to 'true', then all transactions of a given categoryId, as well as all transactions of any of its sub-categories will be regarded. If set to 'false', then sub-categories of a given categoryId will not be regarded and only those transactions are regarded whose category matches one of the explicitly given categoryIds. The default value for this flag is 'true'. (default to true)
     * @param {Boolean} opts.isNew If specified, then only transactions that have their 'isNew' flag set to true/false will be regarded.
     * @param {Boolean} opts.isPotentialDuplicate If specified, then only transactions that have their 'isPotentialDuplicate' flag set to true/false will be regarded.
     * @param {Boolean} opts.isAdjustingEntry If specified, then only transactions that have their 'isAdjustingEntry' flag set to true/false will be regarded.
     * @param {String} opts.minImportDate Lower bound for a transaction's import date, in the format 'YYYY-MM-DD' (e.g. '2016-01-01'). If specified, then only transactions whose 'importDate' is equal to or later than the given date will be regarded.
     * @param {String} opts.maxImportDate Upper bound for a transaction's import date, in the format 'YYYY-MM-DD' (e.g. '2016-01-01'). If specified, then only transactions whose 'importDate' is equal to or earlier than the given date will be regarded.
     * @param {Number} opts.page Result page that you want to retrieve. (default to 1)
     * @param {Number} opts.perPage Maximum number of records per page. By default it's 20. Can be at most 500. NOTE: Due to its validation and visualization, the swagger frontend might show very low performance, or even crashes, when a service responds with a lot of data. It is recommended to use a HTTP client like Postman or DHC instead of our swagger frontend for service calls with large page sizes. (default to 20)
     * @param {Array.<String>} opts.order Determines the order of the results. You can use the following fields for ordering the response: 'id', 'parentId', 'accountId', 'valueDate', 'bankBookingDate', 'finapiBookingDate', 'amount', 'purpose', 'counterpartName', 'counterpartAccountNumber', 'counterpartIban', 'counterpartBlz', 'counterpartBic', 'type', 'primanota', 'category.id', 'category.name', 'isPotentialDuplicate', 'isNew' and 'importDate'. The default order for all services is 'id,asc'. You can also order by multiple properties. In that case the order of the parameters passed is important. Example: '/transactions?order=finapiBookingDate,desc&order=counterpartName' will return the latest transactions first. If there are more transactions on the same day, then these transactions are ordered by the counterpart name (ascending). The general format is: 'property[,asc|desc]', with 'asc' being the default value. Please note that ordering by multiple fields is not supported in our swagger frontend, but you can test this feature with any HTTP tool of your choice (e.g. postman or DHC). 
     * @param {module:api/TransactionsApi~getAndSearchAllTransactionsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PageableTransactionList}
     */
    this.getAndSearchAllTransactions = function(view, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'view' is set
      if (view === undefined || view === null) {
        throw new Error("Missing the required parameter 'view' when calling getAndSearchAllTransactions");
      }


      var pathParams = {
      };
      var queryParams = {
        'view': view,
        'search': opts['search'],
        'counterpart': opts['counterpart'],
        'purpose': opts['purpose'],
        'minBankBookingDate': opts['minBankBookingDate'],
        'maxBankBookingDate': opts['maxBankBookingDate'],
        'minFinapiBookingDate': opts['minFinapiBookingDate'],
        'maxFinapiBookingDate': opts['maxFinapiBookingDate'],
        'minAmount': opts['minAmount'],
        'maxAmount': opts['maxAmount'],
        'direction': opts['direction'],
        'includeChildCategories': opts['includeChildCategories'],
        'isNew': opts['isNew'],
        'isPotentialDuplicate': opts['isPotentialDuplicate'],
        'isAdjustingEntry': opts['isAdjustingEntry'],
        'minImportDate': opts['minImportDate'],
        'maxImportDate': opts['maxImportDate'],
        'page': opts['page'],
        'perPage': opts['perPage'],
      };
      var collectionQueryParams = {
        'ids': {
          value: opts['ids'],
          collectionFormat: 'multi'
        },
        'accountIds': {
          value: opts['accountIds'],
          collectionFormat: 'multi'
        },
        'labelIds': {
          value: opts['labelIds'],
          collectionFormat: 'multi'
        },
        'categoryIds': {
          value: opts['categoryIds'],
          collectionFormat: 'multi'
        },
        'order': {
          value: opts['order'],
          collectionFormat: 'multi'
        },
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['finapi_auth'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PageableTransactionList;

      return this.apiClient.callApi(
        '/api/v1/transactions', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getMultipleTransactions operation.
     * @callback module:api/TransactionsApi~getMultipleTransactionsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TransactionList} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get multiple transactions
     * Get a list of multiple transactions of the user that is authorized by the access_token. Must pass the transactions' identifiers and the user's access_token. Transactions whose identifiers do not exist or do not relate to the authorized user will not be contained in the result (If this applies to all of the given identifiers, then the result will be an empty list). WARNING: This service is deprecated and will be removed at some point. If you want to get multiple transactions, please instead use the service 'Get and search all transactions', where you can pass a comma-separated list of identifiers.
     * @param {Array.<Number>} ids Comma-separated list of identifiers of requested transactions
     * @param {module:api/TransactionsApi~getMultipleTransactionsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TransactionList}
     */
    this.getMultipleTransactions = function(ids, callback) {
      var postBody = null;

      // verify the required parameter 'ids' is set
      if (ids === undefined || ids === null) {
        throw new Error("Missing the required parameter 'ids' when calling getMultipleTransactions");
      }


      var pathParams = {
        'ids': ids
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['finapi_auth'];
      var contentTypes = [];
      var accepts = [];
      var returnType = TransactionList;

      return this.apiClient.callApi(
        '/api/v1/transactions/{ids}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getTransaction operation.
     * @callback module:api/TransactionsApi~getTransactionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Transaction} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a transaction
     * Get a single transaction of the user that is authorized by the access_token. Must pass the transaction's identifier and the user's access_token.
     * @param {Number} id Identifier of transaction
     * @param {module:api/TransactionsApi~getTransactionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Transaction}
     */
    this.getTransaction = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getTransaction");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['finapi_auth'];
      var contentTypes = [];
      var accepts = [];
      var returnType = Transaction;

      return this.apiClient.callApi(
        '/api/v1/transactions/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the restoreTransaction operation.
     * @callback module:api/TransactionsApi~restoreTransactionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Transaction} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Restore a transaction
     * Restore a previously split transaction. Removes all of its sub-transactions.
     * @param {Number} id Transaction identifier
     * @param {module:api/TransactionsApi~restoreTransactionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Transaction}
     */
    this.restoreTransaction = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling restoreTransaction");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['finapi_auth'];
      var contentTypes = [];
      var accepts = [];
      var returnType = Transaction;

      return this.apiClient.callApi(
        '/api/v1/transactions/{id}/restore', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the splitTransaction operation.
     * @callback module:api/TransactionsApi~splitTransactionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Transaction} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Split a transaction
     * Split a transaction into several logical sub-transactions. If the given transaction is split already, all its current sub-transactions will get deleted before the new sub-transactions will get created.
     * @param {Number} id Transaction identifier
     * @param {module:model/SplitTransactionsParams} body Split transactions parameters
     * @param {module:api/TransactionsApi~splitTransactionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Transaction}
     */
    this.splitTransaction = function(id, body, callback) {
      var postBody = body;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling splitTransaction");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling splitTransaction");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['finapi_auth'];
      var contentTypes = [];
      var accepts = [];
      var returnType = Transaction;

      return this.apiClient.callApi(
        '/api/v1/transactions/{id}/split', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the triggerCategorization operation.
     * @callback module:api/TransactionsApi~triggerCategorizationCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Trigger categorization
     * Triggers finAPI's background categorization process for all uncategorized transactions of the given bank connection(s) (or of all of the user's bank connections, if no bank connection identifiers are passed). The service returns as soon as the categorizations are scheduled. At this point, the bank connections will have their 'categorizationStatus' set to 'PENDING'. Use the service \"Get a bank connection\" or \"Get all bank connections\" to check when the categorization has finished (this is the case when the categorizationStatus has switched to 'READY').<br/><br/>Note that if at least one of the target bank connections is currently locked at the time when you call this service (i.e. the bank connection is currently being updated, or another categorization is already scheduled for it), then no categorization will be triggered at all and the service will respond with HTTP code 422.<br/><br/>Please also note:<br/>&bull; finAPI's background categorization process is executed automatically whenever you import or update a bank connection (though in case of update, it will categorize only the new transactions, and not re-run categorization for previously imported transactions). This means that in general you do not have to call this service after an import or update. Use this service only when you wish to re-run the categorization of all existing uncategorized transactions.<br/>&bull; if you wish to just manually assign categories to transactions, please use the service \"Edit a transaction\" or \"Edit multiple transactions\" instead.
     * @param {module:model/TriggerCategorizationParams} body Trigger categorization parameters
     * @param {module:api/TransactionsApi~triggerCategorizationCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.triggerCategorization = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling triggerCategorization");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['finapi_auth'];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/transactions/triggerCategorization', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
