/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FinApiResTfulServices);
  }
}(this, function(expect, FinApiResTfulServices) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AccountParams', function() {
      beforeEach(function() {
        instance = new FinApiResTfulServices.AccountParams();
      });

      it('should create an instance of AccountParams', function() {
        // TODO: update the code to test AccountParams
        expect(instance).to.be.a(FinApiResTfulServices.AccountParams);
      });

      it('should have the property accountName (base name: "accountName")', function() {
        // TODO: update the code to test the property accountName
        expect(instance).to.have.property('accountName');
        // expect(instance.accountName).to.be(expectedValueLiteral);
      });

      it('should have the property accountTypeId (base name: "accountTypeId")', function() {
        // TODO: update the code to test the property accountTypeId
        expect(instance).to.have.property('accountTypeId');
        // expect(instance.accountTypeId).to.be(expectedValueLiteral);
      });

      it('should have the property accountType (base name: "accountType")', function() {
        // TODO: update the code to test the property accountType
        expect(instance).to.have.property('accountType');
        // expect(instance.accountType).to.be(expectedValueLiteral);
      });

      it('should have the property isNew (base name: "isNew")', function() {
        // TODO: update the code to test the property isNew
        expect(instance).to.have.property('isNew');
        // expect(instance.isNew).to.be(expectedValueLiteral);
      });

    });
  });

}));
