/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FinApiResTfulServices);
  }
}(this, function(expect, FinApiResTfulServices) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('BankConnectionInterface', function() {
      beforeEach(function() {
        instance = new FinApiResTfulServices.BankConnectionInterface();
      });

      it('should create an instance of BankConnectionInterface', function() {
        // TODO: update the code to test BankConnectionInterface
        expect(instance).to.be.a(FinApiResTfulServices.BankConnectionInterface);
      });

      it('should have the property _interface (base name: "interface")', function() {
        // TODO: update the code to test the property _interface
        expect(instance).to.have.property('_interface');
        // expect(instance._interface).to.be(expectedValueLiteral);
      });

      it('should have the property loginCredentials (base name: "loginCredentials")', function() {
        // TODO: update the code to test the property loginCredentials
        expect(instance).to.have.property('loginCredentials');
        // expect(instance.loginCredentials).to.be(expectedValueLiteral);
      });

      it('should have the property defaultTwoStepProcedureId (base name: "defaultTwoStepProcedureId")', function() {
        // TODO: update the code to test the property defaultTwoStepProcedureId
        expect(instance).to.have.property('defaultTwoStepProcedureId');
        // expect(instance.defaultTwoStepProcedureId).to.be(expectedValueLiteral);
      });

      it('should have the property twoStepProcedures (base name: "twoStepProcedures")', function() {
        // TODO: update the code to test the property twoStepProcedures
        expect(instance).to.have.property('twoStepProcedures');
        // expect(instance.twoStepProcedures).to.be(expectedValueLiteral);
      });

      it('should have the property aisConsent (base name: "aisConsent")', function() {
        // TODO: update the code to test the property aisConsent
        expect(instance).to.have.property('aisConsent');
        // expect(instance.aisConsent).to.be(expectedValueLiteral);
      });

      it('should have the property lastManualUpdate (base name: "lastManualUpdate")', function() {
        // TODO: update the code to test the property lastManualUpdate
        expect(instance).to.have.property('lastManualUpdate');
        // expect(instance.lastManualUpdate).to.be(expectedValueLiteral);
      });

      it('should have the property lastAutoUpdate (base name: "lastAutoUpdate")', function() {
        // TODO: update the code to test the property lastAutoUpdate
        expect(instance).to.have.property('lastAutoUpdate');
        // expect(instance.lastAutoUpdate).to.be(expectedValueLiteral);
      });

    });
  });

}));
