/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FinApiResTfulServices);
  }
}(this, function(expect, FinApiResTfulServices) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CashFlow', function() {
      beforeEach(function() {
        instance = new FinApiResTfulServices.CashFlow();
      });

      it('should create an instance of CashFlow', function() {
        // TODO: update the code to test CashFlow
        expect(instance).to.be.a(FinApiResTfulServices.CashFlow);
      });

      it('should have the property category (base name: "category")', function() {
        // TODO: update the code to test the property category
        expect(instance).to.have.property('category');
        // expect(instance.category).to.be(expectedValueLiteral);
      });

      it('should have the property income (base name: "income")', function() {
        // TODO: update the code to test the property income
        expect(instance).to.have.property('income');
        // expect(instance.income).to.be(expectedValueLiteral);
      });

      it('should have the property spending (base name: "spending")', function() {
        // TODO: update the code to test the property spending
        expect(instance).to.have.property('spending');
        // expect(instance.spending).to.be(expectedValueLiteral);
      });

      it('should have the property balance (base name: "balance")', function() {
        // TODO: update the code to test the property balance
        expect(instance).to.have.property('balance');
        // expect(instance.balance).to.be(expectedValueLiteral);
      });

      it('should have the property countIncomeTransactions (base name: "countIncomeTransactions")', function() {
        // TODO: update the code to test the property countIncomeTransactions
        expect(instance).to.have.property('countIncomeTransactions');
        // expect(instance.countIncomeTransactions).to.be(expectedValueLiteral);
      });

      it('should have the property countSpendingTransactions (base name: "countSpendingTransactions")', function() {
        // TODO: update the code to test the property countSpendingTransactions
        expect(instance).to.have.property('countSpendingTransactions');
        // expect(instance.countSpendingTransactions).to.be(expectedValueLiteral);
      });

      it('should have the property countAllTransactions (base name: "countAllTransactions")', function() {
        // TODO: update the code to test the property countAllTransactions
        expect(instance).to.have.property('countAllTransactions');
        // expect(instance.countAllTransactions).to.be(expectedValueLiteral);
      });

    });
  });

}));
