/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FinApiResTfulServices);
  }
}(this, function(expect, FinApiResTfulServices) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('EditBankConnectionParams', function() {
      beforeEach(function() {
        instance = new FinApiResTfulServices.EditBankConnectionParams();
      });

      it('should create an instance of EditBankConnectionParams', function() {
        // TODO: update the code to test EditBankConnectionParams
        expect(instance).to.be.a(FinApiResTfulServices.EditBankConnectionParams);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property bankingUserId (base name: "bankingUserId")', function() {
        // TODO: update the code to test the property bankingUserId
        expect(instance).to.have.property('bankingUserId');
        // expect(instance.bankingUserId).to.be(expectedValueLiteral);
      });

      it('should have the property bankingCustomerId (base name: "bankingCustomerId")', function() {
        // TODO: update the code to test the property bankingCustomerId
        expect(instance).to.have.property('bankingCustomerId');
        // expect(instance.bankingCustomerId).to.be(expectedValueLiteral);
      });

      it('should have the property bankingPin (base name: "bankingPin")', function() {
        // TODO: update the code to test the property bankingPin
        expect(instance).to.have.property('bankingPin');
        // expect(instance.bankingPin).to.be(expectedValueLiteral);
      });

      it('should have the property _interface (base name: "interface")', function() {
        // TODO: update the code to test the property _interface
        expect(instance).to.have.property('_interface');
        // expect(instance._interface).to.be(expectedValueLiteral);
      });

      it('should have the property loginCredentials (base name: "loginCredentials")', function() {
        // TODO: update the code to test the property loginCredentials
        expect(instance).to.have.property('loginCredentials');
        // expect(instance.loginCredentials).to.be(expectedValueLiteral);
      });

      it('should have the property defaultTwoStepProcedureId (base name: "defaultTwoStepProcedureId")', function() {
        // TODO: update the code to test the property defaultTwoStepProcedureId
        expect(instance).to.have.property('defaultTwoStepProcedureId');
        // expect(instance.defaultTwoStepProcedureId).to.be(expectedValueLiteral);
      });

    });
  });

}));
