/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FinApiResTfulServices);
  }
}(this, function(expect, FinApiResTfulServices) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('EditTppCredentialParams', function() {
      beforeEach(function() {
        instance = new FinApiResTfulServices.EditTppCredentialParams();
      });

      it('should create an instance of EditTppCredentialParams', function() {
        // TODO: update the code to test EditTppCredentialParams
        expect(instance).to.be.a(FinApiResTfulServices.EditTppCredentialParams);
      });

      it('should have the property tppAuthenticationGroupId (base name: "tppAuthenticationGroupId")', function() {
        // TODO: update the code to test the property tppAuthenticationGroupId
        expect(instance).to.have.property('tppAuthenticationGroupId');
        // expect(instance.tppAuthenticationGroupId).to.be(expectedValueLiteral);
      });

      it('should have the property label (base name: "label")', function() {
        // TODO: update the code to test the property label
        expect(instance).to.have.property('label');
        // expect(instance.label).to.be(expectedValueLiteral);
      });

      it('should have the property tppClientId (base name: "tppClientId")', function() {
        // TODO: update the code to test the property tppClientId
        expect(instance).to.have.property('tppClientId');
        // expect(instance.tppClientId).to.be(expectedValueLiteral);
      });

      it('should have the property tppClientSecret (base name: "tppClientSecret")', function() {
        // TODO: update the code to test the property tppClientSecret
        expect(instance).to.have.property('tppClientSecret');
        // expect(instance.tppClientSecret).to.be(expectedValueLiteral);
      });

      it('should have the property tppApiKey (base name: "tppApiKey")', function() {
        // TODO: update the code to test the property tppApiKey
        expect(instance).to.have.property('tppApiKey');
        // expect(instance.tppApiKey).to.be(expectedValueLiteral);
      });

      it('should have the property validFromDate (base name: "validFromDate")', function() {
        // TODO: update the code to test the property validFromDate
        expect(instance).to.have.property('validFromDate');
        // expect(instance.validFromDate).to.be(expectedValueLiteral);
      });

      it('should have the property validUntilDate (base name: "validUntilDate")', function() {
        // TODO: update the code to test the property validUntilDate
        expect(instance).to.have.property('validUntilDate');
        // expect(instance.validUntilDate).to.be(expectedValueLiteral);
      });

    });
  });

}));
