/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FinApiResTfulServices);
  }
}(this, function(expect, FinApiResTfulServices) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('MockBatchUpdateParams', function() {
      beforeEach(function() {
        instance = new FinApiResTfulServices.MockBatchUpdateParams();
      });

      it('should create an instance of MockBatchUpdateParams', function() {
        // TODO: update the code to test MockBatchUpdateParams
        expect(instance).to.be.a(FinApiResTfulServices.MockBatchUpdateParams);
      });

      it('should have the property mockBankConnectionUpdates (base name: "mockBankConnectionUpdates")', function() {
        // TODO: update the code to test the property mockBankConnectionUpdates
        expect(instance).to.have.property('mockBankConnectionUpdates');
        // expect(instance.mockBankConnectionUpdates).to.be(expectedValueLiteral);
      });

      it('should have the property triggerNotifications (base name: "triggerNotifications")', function() {
        // TODO: update the code to test the property triggerNotifications
        expect(instance).to.have.property('triggerNotifications');
        // expect(instance.triggerNotifications).to.be(expectedValueLiteral);
      });

    });
  });

}));
