/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FinApiResTfulServices);
  }
}(this, function(expect, FinApiResTfulServices) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Paging', function() {
      beforeEach(function() {
        instance = new FinApiResTfulServices.Paging();
      });

      it('should create an instance of Paging', function() {
        // TODO: update the code to test Paging
        expect(instance).to.be.a(FinApiResTfulServices.Paging);
      });

      it('should have the property page (base name: "page")', function() {
        // TODO: update the code to test the property page
        expect(instance).to.have.property('page');
        // expect(instance.page).to.be(expectedValueLiteral);
      });

      it('should have the property perPage (base name: "perPage")', function() {
        // TODO: update the code to test the property perPage
        expect(instance).to.have.property('perPage');
        // expect(instance.perPage).to.be(expectedValueLiteral);
      });

      it('should have the property pageCount (base name: "pageCount")', function() {
        // TODO: update the code to test the property pageCount
        expect(instance).to.have.property('pageCount');
        // expect(instance.pageCount).to.be(expectedValueLiteral);
      });

      it('should have the property totalCount (base name: "totalCount")', function() {
        // TODO: update the code to test the property totalCount
        expect(instance).to.have.property('totalCount');
        // expect(instance.totalCount).to.be(expectedValueLiteral);
      });

    });
  });

}));
