/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FinApiResTfulServices);
  }
}(this, function(expect, FinApiResTfulServices) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PaymentExecutionResponse', function() {
      beforeEach(function() {
        instance = new FinApiResTfulServices.PaymentExecutionResponse();
      });

      it('should create an instance of PaymentExecutionResponse', function() {
        // TODO: update the code to test PaymentExecutionResponse
        expect(instance).to.be.a(FinApiResTfulServices.PaymentExecutionResponse);
      });

      it('should have the property successMessage (base name: "successMessage")', function() {
        // TODO: update the code to test the property successMessage
        expect(instance).to.have.property('successMessage');
        // expect(instance.successMessage).to.be(expectedValueLiteral);
      });

      it('should have the property warnMessage (base name: "warnMessage")', function() {
        // TODO: update the code to test the property warnMessage
        expect(instance).to.have.property('warnMessage');
        // expect(instance.warnMessage).to.be(expectedValueLiteral);
      });

      it('should have the property paymentId (base name: "paymentId")', function() {
        // TODO: update the code to test the property paymentId
        expect(instance).to.have.property('paymentId');
        // expect(instance.paymentId).to.be(expectedValueLiteral);
      });

    });
  });

}));
