/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FinApiResTfulServices);
  }
}(this, function(expect, FinApiResTfulServices) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SingleMoneyTransferRecipientData', function() {
      beforeEach(function() {
        instance = new FinApiResTfulServices.SingleMoneyTransferRecipientData();
      });

      it('should create an instance of SingleMoneyTransferRecipientData', function() {
        // TODO: update the code to test SingleMoneyTransferRecipientData
        expect(instance).to.be.a(FinApiResTfulServices.SingleMoneyTransferRecipientData);
      });

      it('should have the property recipientName (base name: "recipientName")', function() {
        // TODO: update the code to test the property recipientName
        expect(instance).to.have.property('recipientName');
        // expect(instance.recipientName).to.be(expectedValueLiteral);
      });

      it('should have the property recipientIban (base name: "recipientIban")', function() {
        // TODO: update the code to test the property recipientIban
        expect(instance).to.have.property('recipientIban');
        // expect(instance.recipientIban).to.be(expectedValueLiteral);
      });

      it('should have the property recipientBic (base name: "recipientBic")', function() {
        // TODO: update the code to test the property recipientBic
        expect(instance).to.have.property('recipientBic');
        // expect(instance.recipientBic).to.be(expectedValueLiteral);
      });

      it('should have the property clearingAccountId (base name: "clearingAccountId")', function() {
        // TODO: update the code to test the property clearingAccountId
        expect(instance).to.have.property('clearingAccountId');
        // expect(instance.clearingAccountId).to.be(expectedValueLiteral);
      });

      it('should have the property endToEndId (base name: "endToEndId")', function() {
        // TODO: update the code to test the property endToEndId
        expect(instance).to.have.property('endToEndId');
        // expect(instance.endToEndId).to.be(expectedValueLiteral);
      });

      it('should have the property amount (base name: "amount")', function() {
        // TODO: update the code to test the property amount
        expect(instance).to.have.property('amount');
        // expect(instance.amount).to.be(expectedValueLiteral);
      });

      it('should have the property purpose (base name: "purpose")', function() {
        // TODO: update the code to test the property purpose
        expect(instance).to.have.property('purpose');
        // expect(instance.purpose).to.be(expectedValueLiteral);
      });

      it('should have the property sepaPurposeCode (base name: "sepaPurposeCode")', function() {
        // TODO: update the code to test the property sepaPurposeCode
        expect(instance).to.have.property('sepaPurposeCode');
        // expect(instance.sepaPurposeCode).to.be(expectedValueLiteral);
      });

    });
  });

}));
