/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FinApiResTfulServices);
  }
}(this, function(expect, FinApiResTfulServices) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SingleDirectDebitData', function() {
      beforeEach(function() {
        instance = new FinApiResTfulServices.SingleDirectDebitData();
      });

      it('should create an instance of SingleDirectDebitData', function() {
        // TODO: update the code to test SingleDirectDebitData
        expect(instance).to.be.a(FinApiResTfulServices.SingleDirectDebitData);
      });

      it('should have the property debitorName (base name: "debitorName")', function() {
        // TODO: update the code to test the property debitorName
        expect(instance).to.have.property('debitorName');
        // expect(instance.debitorName).to.be(expectedValueLiteral);
      });

      it('should have the property debitorIban (base name: "debitorIban")', function() {
        // TODO: update the code to test the property debitorIban
        expect(instance).to.have.property('debitorIban');
        // expect(instance.debitorIban).to.be(expectedValueLiteral);
      });

      it('should have the property debitorBic (base name: "debitorBic")', function() {
        // TODO: update the code to test the property debitorBic
        expect(instance).to.have.property('debitorBic');
        // expect(instance.debitorBic).to.be(expectedValueLiteral);
      });

      it('should have the property amount (base name: "amount")', function() {
        // TODO: update the code to test the property amount
        expect(instance).to.have.property('amount');
        // expect(instance.amount).to.be(expectedValueLiteral);
      });

      it('should have the property purpose (base name: "purpose")', function() {
        // TODO: update the code to test the property purpose
        expect(instance).to.have.property('purpose');
        // expect(instance.purpose).to.be(expectedValueLiteral);
      });

      it('should have the property sepaPurposeCode (base name: "sepaPurposeCode")', function() {
        // TODO: update the code to test the property sepaPurposeCode
        expect(instance).to.have.property('sepaPurposeCode');
        // expect(instance.sepaPurposeCode).to.be(expectedValueLiteral);
      });

      it('should have the property mandateId (base name: "mandateId")', function() {
        // TODO: update the code to test the property mandateId
        expect(instance).to.have.property('mandateId');
        // expect(instance.mandateId).to.be(expectedValueLiteral);
      });

      it('should have the property mandateDate (base name: "mandateDate")', function() {
        // TODO: update the code to test the property mandateDate
        expect(instance).to.have.property('mandateDate');
        // expect(instance.mandateDate).to.be(expectedValueLiteral);
      });

      it('should have the property creditorId (base name: "creditorId")', function() {
        // TODO: update the code to test the property creditorId
        expect(instance).to.have.property('creditorId');
        // expect(instance.creditorId).to.be(expectedValueLiteral);
      });

      it('should have the property endToEndId (base name: "endToEndId")', function() {
        // TODO: update the code to test the property endToEndId
        expect(instance).to.have.property('endToEndId');
        // expect(instance.endToEndId).to.be(expectedValueLiteral);
      });

    });
  });

}));
