/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.92.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FinApiResTfulServices);
  }
}(this, function(expect, FinApiResTfulServices) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('UserUpdateParams', function() {
      beforeEach(function() {
        instance = new FinApiResTfulServices.UserUpdateParams();
      });

      it('should create an instance of UserUpdateParams', function() {
        // TODO: update the code to test UserUpdateParams
        expect(instance).to.be.a(FinApiResTfulServices.UserUpdateParams);
      });

      it('should have the property email (base name: "email")', function() {
        // TODO: update the code to test the property email
        expect(instance).to.have.property('email');
        // expect(instance.email).to.be(expectedValueLiteral);
      });

      it('should have the property phone (base name: "phone")', function() {
        // TODO: update the code to test the property phone
        expect(instance).to.have.property('phone');
        // expect(instance.phone).to.be(expectedValueLiteral);
      });

      it('should have the property isAutoUpdateEnabled (base name: "isAutoUpdateEnabled")', function() {
        // TODO: update the code to test the property isAutoUpdateEnabled
        expect(instance).to.have.property('isAutoUpdateEnabled');
        // expect(instance.isAutoUpdateEnabled).to.be(expectedValueLiteral);
      });

    });
  });

}));
